
<div id="templatemo_slider_wrapper">
	<div id="templatemo_slider">
		<h1>About Us</h1>
<?php echo $yesterday =  date("Y-m-d", strtotime("-1 day") ); ?>
        <p>In ac libero urna. Suspendisse sed odio ut mi auctor blandit. Duis luctus nulla metus, a vulputate mauris. Integer sed nisi sapien, ut gravida mauris. Nam et tellus libero. Cras purus libero, dapibus nec rutrum in, dapibus nec risus. </p>
        <p>Ut interdum mi sit amet magna feugiat auctor. Vestibulum sapien sapien, tempor in hendrerit et, facilisis at magna. <a href="#">Vestibulum consectetur</a> mi id sapien placerat a eleifend tortor tempor. <a href="#">Phasellus blandit</a> euismod congue. Nunc pretium scelerisque volutpat. Morbi non lectus nulla. Pellentesque tortor sem, elementum vitae vestibulum eu, dapibus ac risus.</p>
	</div>
</div>

<div id="templatemo_top_row_wrapper">
	<div id="templatemo_top_row">

    	<div class="top_row_box">
        	<h5>Morbi sed nulla ac est</h5>
          <p>Aliquam leo lectus, tempor ac hendrerit in, laoreet et nibh mi vulputate aliquam. </p>
            <div class="button"><a href="#">More</a></div>
        </div>

        <div class="top_row_box">
        	<h5>Curabitur ullamcorper</h5>
          <p>Nam malesuada bibendum metus ac faucibus nunc augue luctus sem. </p>
            <div class="button"><a href="#">More</a></div>
        </div>

        <div class="top_row_box last">
        	<h5>Fusce pharetra pharetra </h5>
          <p>Maecenas nisl est, interdum id mollis sed, venenatis id tellus. </p>
            <div class="button"><a href="#">More</a></div>
        </div>

    	<div class="cleaner"></div>
    </div> <!-- end of top row -->
</div> <!-- end of top row wrapper -->

<div id="templatemo_content_wrapper">
	<div id="templatemo_content">

            <div class="two_column float_l">

                <h2>Our Standards</h2>
                 <p>Nunc sed pharetra dui. Donec malesuada rutrum imperdiet. Etiam nec risus sit amet diam malesuada dictum non vitae est. </p>


                 <ul>
                    <li>Vestibulum auctor euismod mi</li>
                    <li>Phasellus diam orci, rhoncus</li>
                    <li>Sed condimentum ornare ipsum</li>
                    <li>Nam malesuada bibendum metus ac </li>
                    <li>Maecenas nisl est, interdum id mollis </li>
                </ul>

                <div class="button"><a href="#">More</a></div>

            </div>


            <div class="two_column float_r">

                 <h2>Testimonials</h2>
                <blockquote>
                <p>Aliquam dapibus euismod placerat. Aliquam a lacus sem, ac pharetra neque. Sed luctus sodales iaculis. Nullam consectetur odio eget lorem placerat et ullamcorper sapien fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>

                <cite>Web Designer - <a href="http://www.templatemo.com" target="_parent">templatemo.com</a></cite>                </blockquote>

            </div>

    	<div class="cleaner"></div>
	</div> <!-- end of content -->
</div> <!-- end of content_wrapper -->