<?php session_start() ;?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0">
    <link rel="icon" type="image/png" href="<?php echo $iniObj->UIPath; ?>/img/favicon.png">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/buttons.bootstrap5.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/main.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/style.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/select2.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/all.css">
    <title>GEMO</title>

    <script src="<?php echo $iniObj->UIPath; ?>/js/jquery-3.5.1.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.0/chart.min.js" integrity="sha512-asxKqQghC1oBShyhiBwA+YgotaSYKxGP1rcSYTDrB0U6DxwlJjU59B67U8+5/++uFjcuVM8Hh5cokLjZlhm3Vg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>