
<script defer src="<?php echo $iniObj->UIPath; ?>/js/jquery.dataTables.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/select2.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/dataTables.responsive.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/jszip.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/pdfmake.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/dataTables.buttons.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/vfs_fonts.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/buttons.html5.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/js/main.js"></script>

</body>

</html>