<!-- Sidemenu --> 
<div class="main-sidebar main-sidebar-sticky side-menu ps ps--active-y">
      <div class="sidemenu-logo"> <a class="main-logo" href="<?php $lib->customerSite ?>/dashboard"> 
      <img src="<?php $lib->customerSite ?>/UIResources/logo_dash.png" class="header-brand-img desktop-logo" alt="Logo GEMO"> 
      <img src="<?php $lib->customerSite ?>/UIResources/logo_dash_mini.png" class="header-brand-img icon-logo" alt="logo"> 
      <img src="<?php $lib->customerSite ?>/UIResources/logo_dash.png" class="header-brand-img desktop-logo theme-logo" alt="Logo GEMO"> 
      <img src="<?php $lib->customerSite ?>/UIResources/logo_dash_mini.png" class="header-brand-img icon-logo theme-logo" alt="Logo GEMO"> </a> </div>
      <div class="main-sidebar-body">
         <ul class="nav">
            <li class="nav-header"><span class="nav-label text-warning">Tableau de bord</span></li>
            <li class="nav-item <?php $url_array[1] === 'dashboard'?  'active' : '' ?>"> <a class="nav-link" href="<?php $lib->customerSite ?>/dashboard"><span class="shape1"></span><span class="shape2"></span><i class="ti-home sidemenu-icon"></i><span class="sidemenu-label">Tableau de bord</span></a> </li>

            <?php if($_SESSION['access'] ==='1'):?>

            <li class="nav-item">
               <a class="nav-link with-sub" href="#"><span class="shape1"></span><span class="shape2"></span><i class="ti-wallet sidemenu-icon"></i><span class="sidemenu-label">Opérations</span><i class="angle fe fe-chevron-right"></i></a> 
               <ul class="nav-sub">
                  <li class="nav-sub-item"> <a class="nav-sub-link" href="<?php $lib->customerSite ?>/operation/historique">Historiques</a> </li>
               </ul>
            </li>

            <li class="nav-item">
               <a class="nav-link with-sub" href="#"><span class="shape1"></span><span class="shape2"></span><i class="ti-shopping-cart-full sidemenu-icon"></i><span class="sidemenu-label">Administration</span><i class="angle fe fe-chevron-right"></i></a> 
               <ul class="nav-sub">
                  <li class="nav-sub-item"> <a class="nav-sub-link" href="<?php $lib->customerSite ?>/administration/agent/liste">Licences</a> </li>
                  <li class="nav-sub-item"> <a class="nav-sub-link" href="<?php $lib->customerSite ?>/administration/utilisateurs/liste">Utilisateurs</a> </li>
                  <li class="nav-sub-item"> <a class="nav-sub-link" href="<?php $lib->customerSite ?>/administration/inventaire/liste">Inventaires</a> </li>
               </ul>
            </li>

            <?php endif;?>

         </ul>
      </div>
      <div class="ps__rail-x" style="left: 0px; top: 0px;">
         <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
      </div>
      <div class="ps__rail-y" style="top: 0px; height: 466px; right: 0px;">
         <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 198px;"></div>
      </div>
   </div>
   <!-- End Sidemenu -->