<?php session_start() ;?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0">
    <meta http-equiv="imagetoolbar" content="no" />
    <link rel="icon" type="image/png" href="<?php echo $iniObj->UIPath; ?>/img/favicon.png">
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet"/> <!-- Icons css--> 
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/web-fonts/icons.css" rel="stylesheet"/>
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/web-fonts/font-awesome/font-awesome.min.css" rel="stylesheet">
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/web-fonts/plugin.css" rel="stylesheet"/> <!-- Style css--> 
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/css/style.css" rel="stylesheet">
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/css/skins.css" rel="stylesheet">
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/css/dark-style.css" rel="stylesheet">
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/css/colors/default.css" rel="stylesheet"> <!-- Color css--> 
    <link id="theme" rel="stylesheet" type="text/css" media="all" href="<?php echo $iniObj->UIPath; ?>/dashboard/css/colors/color.css"> <!-- Select2 css--> 
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/select2/css/select2.min.css" rel="stylesheet"> <!-- Mutipleselect css--> 
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/multipleselect/multiple-select.css"> <!-- Sidemenu css--> 
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/css/sidemenu/sidemenu.css" rel="stylesheet"> <!-- Switcher css--> 
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/switcher/css/switcher.css" rel="stylesheet">
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/switcher/demo.css">

    <!-- Internal Morrirs Chart css-->
		<link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/morris.js/morris.css" rel="stylesheet">
        


    <!-- Internal DataTables css-->
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/responsivebootstrap4.min.css" rel="stylesheet" />
    <link href="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/buttons.bootstrap4.min.css" rel="stylesheet" />


    <title>GEMO</title>

</head>
<body class="main-body leftmenu">

<div class="page">