
</div>

<script src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/jquery/jquery.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/bootstrap/js/popper.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/chart.js/Chart.bundle.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/peity/jquery.peity.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/select2/js/select2.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/perfect-scrollbar/perfect-scrollbar.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/sidemenu/sidemenu.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/sidebar/sidebar.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/raphael/raphael.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/morris.js/morris.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/circle-progress.min.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/chart-circle.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/index.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/sticky.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/custom.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/switcher/js/switcher.js" type="text/javascript"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/main.js" type="text/javascript"></script>


<!-- Internal Data Table js -->
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/jquery.dataTables.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/dataTables.bootstrap4.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/dataTables.responsive.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/dataTables.buttons.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/buttons.bootstrap4.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/jszip.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/pdfmake.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/vfs_fonts.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/buttons.html5.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/buttons.print.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/plugins/datatable/fileexport/buttons.colVis.min.js"></script>
<script defer src="<?php echo $iniObj->UIPath; ?>/dashboard/js/table-data.js"></script>

</body>

</html>

