<?php session_start() ;?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0">
    
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/main.css">
   
    <title>GEMO</title>

</head>
<body>