<div id="templatemo_slider_wrapper">
	<div id="templatemo_slider">

        <div id="one" class="contentslider">
        <div class="cs_wrapper">
            <div class="cs_slider">

                <div class="cs_article">

                    <div class="article">

                        <div class="left">
                            <h2>Distribution de musique</h2>
                            <p>Réalisation, conception, maintenance, et hébergement de la plateforme de Musique Vibetrigger.com. </p>
                            <div class="button"><a href="/gallery#vibetrigger">Plus d'infos</a></div>
                        </div>

                        <div class="right">
                            <a href="http://www.vibetrigger.com" target="_parent">
                                <img src="images/slider/templatemo_slide01.jpg" alt="Vibetrigger" />
                            </a>
                        </div>

                    </div>

                </div><!-- End cs_article -->

                <div class="cs_article">
                   <div class="article">

                        <div class="left">
                            <h2>La caverne des Particuliers</h2>
                            <p>Réalisation, conception, maintenance, et hébergement du site e-commerce LaCaverne.com.</p>
                            <div class="button"><a href="/gallery#caverne">Plus d'infos</a></div>
                        </div>

                        <div class="right">
                            <a href="http://www.templatemo.com/page/2" target="_parent">
                                <img src="images/slider/templatemo_slide02.jpg" alt="template 2" />
                            </a>
                        </div>

                    </div>
                </div><!-- End cs_article -->

                <div class="cs_article">
                    <div class="article">

                        <div class="left">
                            <h2>Univers Festif</h2>
                            <p>Réalisation, conception, maintenance, et hébergement du site e-commerce Univers-Festif.fr .</p>
                            <div class="button"><a href="/gallery#univers">Plus d'infos</a></div>
                        </div>

                        <div class="right">
                            <a href="http://www.univers-Festif.fr/" target="_parent">
                                <img src="images/slider/templatemo_slide03.jpg" alt="template 3" />
                            </a>
                        </div>

                    </div>
                </div><!-- End cs_article -->

                <div class="cs_article">
                   <div class="article">

                        <div class="left">
                            <h2>Lorem ipsum dolor sit amet</h2>
                            <p>Duis fermentum sem nec ipsum lacinia fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <div class="button"><a href="#">Plus d'infos</a></div>
                        </div>

                        <div class="right">
                            <a href="http://www.templatemo.com/page/4" target="_parent">
                                <img src="images/slider/templatemo_slide04.jpg" alt="template 4" />
                            </a>
                        </div>

                    </div>
                </div><!-- End cs_article -->

            </div><!-- End cs_slider -->
        </div><!-- End cs_wrapper -->
        </div><!-- End contentslider -->

        <!-- Site JavaScript -->
        <script type="text/javascript" src="js/jquery-1.3.1.min.js"></script>
        <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="js/jquery.ennui.contentslider.js"></script>
        <script type="text/javascript">
        $(function() {
        $('#one').ContentSlider({
        width : '910px',
        height : '210px',
        speed : 500,
        easing : 'easeOutQuart'
        });
        });
        </script>
        <script src="js/jquery.chili-2.2.js" type="text/javascript"></script>
        <script src="js/chili/recipes.js" type="text/javascript"></script>

    </div> <!-- end of slider -->
</div> <!-- end of slider_wrapper -->

<div id="templatemo_top_row_wrapper">
	<div id="templatemo_top_row">

    	<div class="top_row_box">
        	<h5>Gestion de projet</h5>
          <p>Nous vous aidons à gérer vos projets informatiques. </p>
            <div class="button"><a href="/services#gestion">Plus d'infos</a></div>

        </div>

        <div class="top_row_box">
        	<h5>Conception, réalisation</h5>
          <p>Nous vous accompanons dans la réalisation de vos solutions </p>
            <div class="button"><a href="/services#conception">Plus d'infos</a></div>
        </div>

        <div class="top_row_box last">
        	<h5>Hébergement</h5>
          <p>Nous vous . </p>
            <div class="button"><a href="/services#herbergement">Plus d'infos</a></div>
        </div>

    	<div class="cleaner"></div>
    </div> <!-- end of top row -->
</div> <!-- end of top row wrapper -->

<div id="templatemo_content_wrapper">
	<div id="templatemo_content">

        <h1>What we do?</h1>
        <div class="image_wrapper fl_img">
	        <img src="images/templatemo_image_05.jpg" alt="image" width="120" height="120" />        </div>
        <p><a href="http://www.templatemo.com" target="_parent">Extreme Template</a> is provided by  <a href="http://www.templatemo.com/page/1" target="_parent">Free CSS Templates</a>. This template contains total 5 different pages. Mauris risus magna, blandit ac suscipit at, tristique id erat.  Vestibulum malesuada magna a nisi tempor interdum. Pellentesque quis  justo erat. Nam malesuada bibendum metus ac faucibus. </p>
        <p>Integer semper,  felis eget imperdiet commodo, nunc augue luctus sem, a tincidunt dolor  nisl vel massa. Vivamus interdum, tortor at pellentesque pulvinar, diam  quam blandit nulla, non faucibus nisi metus sit amet neque. Etiam eu  ipsum a arcu sodales consequat sit amet at orci. Nulla in luctus elit.  Phasellus pellentesque iaculis nibh, ut suscipit nisl accumsan sit amet.</p>
      <div class="cleaner"></div>
	</div> <!-- end of content -->
</div> <!-- end of content_wrapper -->