<div id="templatemo_content_wrapper">
	<div id="templatemo_content">

        	<h1>Nos services</h1>
         <p> Donec in nisi. Etiam sit amet turpis. Duis nulla diam, posuere ac, varius id, ullamcorper sit amet, libero. Nam sodales, pede vel dapibus lobortis, ipsum diam molestie risus, a vulputate risus nisl pulvinar lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. <a href="#">Praesent aliquam</a> velit a magna sodales quis elementum ipsum auctor.</p>

      <div class="cleaner_h30"></div>

        <div class="services_section">

            <h2>Mise en place de votre solution Internet</h2>
      <div class="two_column float_l">
                <div class="image_wrapper"><img src="images/templatemo_image_03.jpg" alt="image" /></div>
              <p>Nous réalisons votre solution sur mesure, consulter nos <a href="/gallery">nos realisations</a>..</p>
          </div>

            <div class="two_column float_r">
				<ul>
                	<li>Conception et realisation de site statique ou dynamique</li>
                  	<li>Plateforme e-Commerce</li>
                    <li></li>
                    <li></li>
                  	<li></li>
              </ul>

            </div>

			<div class="cleaner"></div>

        </div>

         <div class="services_section">

            <h2>Hebergement de votre solution Internet</h2>
  <div class="two_column float_l">
                <div class="image_wrapper"><img src="images/templatemo_image_02.jpg" alt="image" /></div>
              <p>Nous vous accompagnons dans toutes les phases de votre projet, de la conception jusqu'a l'hebergement.<a href="#"> Aenean condimentum</a> .</p>
           </div>

            <div class="two_column float_r">

                <ul>
                    <li>Mauris risus magna, blandit ac suscipit at, tristique id erat</li>
                    <li>Vestibulum malesuada magna a nisi tempor interdum</li>
                    <li>Pellentesque quis justo erat</li>
                    <li>Nam malesuada bibendum metus ac faucibus</li>
                    <li>Etiam eu ipsum a arcu sodales consequat sit amet at orci</li>
                </ul>

            </div>

			<div class="cleaner"></div>

        </div>

  <div class="services_section">

            <h2>Lorem ipsum dolor sit amet</h2>
            <div class="two_column float_l">
                <div class="image_wrapper"><img src="images/templatemo_image_01.jpg" alt="image" /></div>
              <p>Vivamus interdum, tortor at pellentesque pulvinar, diam quam blandit  nulla, non faucibus nisi metus sit amet neque. Etiam eu ipsum a arcu  sodales consequat sit amet at orci. <a href="#">Nulla in luctus</a> elit. Phasellus  pellentesque iaculis nibh. </p>
      </div>

            <div class="two_column float_r">

                <ul>
                    <li>Pellentesque quis justo erat</li>
                    <li>Nam malesuada bibendum metus ac faucibus</li>
                    <li>Etiam eu ipsum a arcu sodales consequat sit amet at orci</li>
                    <li>Mauris risus magna, blandit ac suscipit at, tristique id erat</li>
                    <li>Vestibulum malesuada magna a nisi tempor interdum</li>
                </ul>

            </div>

			<div class="cleaner"></div>

        </div>

    	<div class="cleaner"></div>
	</div> <!-- end of content -->
</div> <!-- end of content_wrapper -->