<!-- Main Content-->
<div class="main-content side-content pt-0">

<div class="container-fluid">
    <div class="inner-body">

        <!-- Page Header -->
        <div class="page-header">

            <?php include _VIEW_PATH."common_top_for_dashboard_content.phtml"; ?>

        </div>
        <!-- End Page Header -->

        <!-- Row -->
        <div class="row row-sm">
            <div class="col-lg-12">
                <div class="card custom-card">
                    <div class="card-body">
                        <div>
                            <h6 class="main-content-label mb-1">Licences</h6>
                            <!-- <p class="text-muted card-sub-title">Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.</p> -->
                        </div>
                        <div class="table-responsive">
                            <table id="example3" class="table table-striped table-bordered text-nowrap" >
                            <thead>
                                    <tr>
                                        <th>Licence key</th>
                                        <th>Date d'activation</th>
                                        <th>Date d'expiration</th>
                                        <th>Agents associer</th>
                                        <th>Statut</th>
                                        <th style="text-align:center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php if(isset($data['licences'])): ?>
                                        <?php foreach($data['licences'] as $licence): ?>
                                        <tr>
                                             <td><?= $licence['licence_key'] ?></td>
                                             
                                             <td><?=$licence['activation_date'] ?></td>
                                             <td><?=$licence['expiration_date'] ?></td>
                                          
                                            <td><?= isset($licence['user_id']) ? $licence['firstname'] .' '. $licence['lastname'] : 'Pas d\'utilisateur' ?></td>
    
                                             <td>
                                                  <?php if($licence['is_active'] == 1): ?>
                                                       <span class="badge badge-pill badge-success-light">Activer</span>
                                                  <?php endif; ?>
                                                  <?php if($licence['is_active'] == 0): ?>
                                                       <span class="badge badge-pill badge-danger">Bloquer</span>
                                                  <?php endif; ?>
                                                  <!--<?php //if($licence['is_active'] == 2): ?>
                                                       <span class="span-success danger">Revoquer</span>
                                                  <?php //endif; ?>-->
                                             </td>
                                             <td style="text-align:center">

                                                <?php if(!isset($licence['licence_id'])): ?>
                                                <span onclick="document.location='<?php $lib->customerSite ?>/administration/agent/attributionLicence/<?=$licence[0] ?>'" class="btn ripple btn-info ">Attribuer</span>
                                                <?php else: ?>
                                                <span onclick="document.location='<?php $lib->customerSite ?>/administration/agent/attributionLicence/<?=$licence['licence_id'] ?>'" class="btn ripple btn-info ">Attribuer</span>
                                                <?php endif; ?>
                                                
                                                <?php if(isset($licence['user_id'])): ?>
                                                <span onclick="document.location='<?php $lib->customerSite ?>/administration/agent/revocationLicence/<?=$licence['licence_id'] ?>'" class="btn ripple btn-primary">Révoquer</span>
                                                <?php endif; ?>
                                            </td>
    
                                        </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Row -->

       
    </div>
</div>
</div>
<!-- End Main Content-->