<!-- Main Content-->
<div class="main-content side-content pt-0">

    <div class="container-fluid">
        <div class="inner-body">
                <!-- Page Header -->
                <div class="page-header">

					<div>
						<h2 class="main-content-title tx-24 mg-b-5">Agents</h2>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><?= $url_array[1] ?></a></li>
							<li class="breadcrumb-item active" aria-current="page"><?= $url_array[2] ?></li>
                            
						</ol>
					</div>
							
					<div class="d-flex">
						<div class="justify-content-center">
							<button onclick="document.location='<?php $lib->customerSite ?>/managers/agents/ajouter/<?= $url_array[3] ?>'" type="button" class="btn btn-primary my-2 btn-icon-text">
								<i class="fas fa-plus mr-2"></i> Ajouter un nouveau agent
							</button>
						</div>
					</div>

                </div>
                <!-- End Page Header -->

                <!-- Row -->
                <div class="row row-sm">
                    <div class="col-lg-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div>
									<h6 class="main-content-label mb-1">Liste des agents</h6>
								</div>
                                <div class="table-responsive">
                                    <table id="example2" class="table table-striped table-bordered text-nowrap" >
                                    <thead>
										<tr>
                                            <th>Nom et prenom du manager</th>
                                            <th>Téléphone</th>
                                            <th>Email</th>
                                            <th>Date début</th>
                                            <th>Date Expiration</th>
                                            <th>Statut</th>
                                            <th class="">Actions</th>
										</tr>
									</thead>
												<tbody>
                                                <?php if(!empty($data['manager'])):?>
                                                    <?php foreach($data['manager'] as $manager):?>
                                                        <tr>
                                                            <td><?=$manager['firstname']?> <?=$manager['lastname']?></td>
                                                            <td><?=$manager['phone_number']?></td>
                                                            <td><?=$manager['email']?></td>
                                                            <td><?=$manager['active_date_from']?></td>
                                                            <td><?=$manager['active_date_to']?></td>
                                                            <td>
                                                                <?php if($manager['is_active_flag'] == 1): ?>
                                                                    <span class="btn ripple btn-success btn-rounded">Activer</span>
                                                                    
                                                                <?php endif; ?>
                                                                <?php if($manager['is_active_flag'] == 0): ?>
                                                                    <span class="btn ripple btn-danger btn-rounded">Bloquer</span>
                                                                    
                                                                <?php endif; ?>
                                                            </td>
                                                            <td >
                                                                <?php if($manager['is_active_flag'] == 1): ?>
                                                                    <button onclick="document.location='<?php $lib->customerSite ?>/managers/bloquer/<?=$manager['user_id']?>'" class="btn ripple btn-danger">Bloquer</button>
                                                                <?php endif; ?>
                                                                <?php if($manager['is_active_flag'] == 0): ?>
                                                                    <button onclick="document.location='<?php $lib->customerSite ?>/managers/activer/<?=$manager['user_id']?>'" class="btn ripple btn-success">Activer</button>
                                                                <?php endif; ?>
                                                                <!--<span onclick="document.location='<?php $lib->customerSite ?>/managers/activer/<?=$manager['user_id']?>'" class="btn-action white pg-5 cursor success">Activer</span>
                                                                <span onclick="document.location='<?php $lib->customerSite ?>/managers/bloquer/<?=$manager['user_id']?>'" class="btn-action white pg-5 cursor danger">Bloquer</span>-->
                                                                <span onclick="document.location='<?php $lib->customerSite ?>/managers/password/<?=$manager['user_id']?>'" class="btn ripple btn-primary">Modifier le mot de passe</span>
                                                                
                                                            </td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                <?php endif;?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->    
        </div>
    </div>
</div>
<!-- End Main Content-->



			



