 <!-- START Page Banner -->
 <section class="page-banner">
            <div class="container">
                <div class="banner-content text-center">
                    <h2>Blog Details</h2>
                    <div class="page-breadcrumb">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Pages</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Page Banner -->

        <!-- START Blog Details Content -->
        <section class="blog-details py-120 rpy-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="blog-sidebar">
                            <div class="sidebar-widget search-box">
                                <form method="post" action="http://live.envalab.com/html/envotek/contact.html">
                                    <div class="form-group">
                                        <input type="search" name="search-field" value="" placeholder="Search here..." required="">
                                        <button type="submit"><i class="icofont-search-1"></i></button>
                                    </div>
                                </form>
                            </div>
                            <div class="sidebar-widget blog-catagory">
                                <h4>Blog Catagory</h4>
                                <div class="course-module">
                                    <ul>
                                        <li>
                                            <a href="servicedetails.html"><i class="icofont-double-right"></i> Web Design <span>32</span></a>
                                        </li>
                                        <li>
                                            <a href="servicedetails.html"><i class="icofont-double-right"></i> Web Development <span>22</span></a>
                                        </li>
                                        <li>
                                            <a href="servicedetails.html"><i class="icofont-double-right"></i> Graphic Design <span>25</span></a>
                                        </li>
                                        <li>
                                            <a href="servicedetails.html"><i class="icofont-double-right"></i> Online Marketing <span>38</span></a>
                                        </li>
                                        <li>
                                            <a href="servicedetails.html"><i class="icofont-double-right"></i> App Development <span>26</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sidebar-widget archive-post">
                                <h4>Archive Post</h4>
                                <div class="posting-content">
                                    <div class="posting-date">
                                        <p><i class="icofont-calendar"></i> 25 August 2021</p>
                                    </div>
                                    <h6><a href="blogdetails.html">Duis autem eum iriure dolor emn hendrerit consequa vel illum eu feugiat nulla.</a></h6>
                                </div>
                                <div class="posting-content">
                                    <div class="posting-date">
                                        <p><i class="icofont-calendar"></i> 25 August 2021</p>
                                    </div>
                                    <h6><a href="blogdetails.html">Duis autem eum iriure dolor emn hendrerit consequa vel illum eu feugiat nulla.</a></h6>
                                </div>
                                <div class="posting-content">
                                    <div class="posting-date">
                                        <p><i class="icofont-calendar"></i> 25 August 2021</p>
                                    </div>
                                    <h6><a href="blogdetails.html">Duis autem eum iriure dolor emn hendrerit consequa vel illum eu feugiat nulla.</a></h6>
                                </div>
                                <div class="posting-content">
                                    <div class="posting-date">
                                        <p><i class="icofont-calendar"></i> 25 August 2021</p>
                                    </div>
                                    <h6><a href="blogdetails.html">Duis autem eum iriure dolor emn hendrerit consequa vel illum eu feugiat nulla.</a></h6>
                                </div>
                            </div>
                            <div class="sidebar-widget blog-video-widget">
                                <a class="video-play mfp-iframe" href="https://www.youtube.com/watch?v=aFWhf2wjJYo&amp;list=PLUoqTnNH-2XxOt7UsKlTqbfrA2ucGosCR">
                                    <i class="icofont-ui-play"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="blog-details-content">
                            <div class="blog-details-image">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/blog/blog-details1.jpg" alt="Blog Details Image One" />
                                <div class="blog-publish-date">
                                    <span>22 June</span>
                                </div>
                            </div>
                            <h3>The Best IT Practices in Cloud And Security.</h3>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of scrambled it to make a type specimen book. It has survived not only five centuries, but also the electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with Letraset sheets containing Lorem Ipsum passages.</p>
                            <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining unchanged. It was popular of the reease and more recent. Lorem Ipsum is simply dummy printing and typesetting industry.</blockquote>
                            <div class="blog-middle-image">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/blog/blog-details2.jpg" alt="Blog Details Image Two" />
                            </div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with Letraset sheets containing Lorem Ipsum passages.</p>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of electronic typesetting, remaining essentially unchanged.</p>
                            <h3>Help challenge critical activities</h3>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with Letraset sheets containing Lorem Ipsum passages.</p>
                            <div class="tags">
                                <ul>
                                    <li>Tags: </li>
                                    <li><a href="#">Medical,</a></li>
                                    <li><a href="#"> Doctors,</a></li>
                                    <li><a href="#">Theraphi</a></li>
                                </ul>
                            </div>
                            <div class="comment-box">
                                <h4>Comments</h4>
                                <div class="comment">
                                    <div class="commenter-image">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/blog/commenter1.jpg" alt="Commenter" />
                                    </div>
                                    <div class="commenter-info">
                                        <div class="commenter-info-top">
                                            <div class="commenter-name">
                                                <h5>Mayra Bolin</h5>
                                                <span>Web Developer</span>
                                            </div>
                                            <a href="#" class="comment-reply"><i class="icofont-reply"></i> Reply</a>
                                        </div>
                                        <p>It is a long established fact that a reader will be distracted by the readable cont ent of a he point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters content here', making.</p>
                                    </div>
                                </div>
                                <div class="comment style-two">
                                    <div class="commenter-image">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/blog/commenter2.jpg" alt="Commenter" />
                                    </div>
                                    <div class="commenter-info">
                                        <div class="commenter-info-top">
                                            <div class="commenter-name">
                                                <h5>Rafaela Levy</h5>
                                                <span>Web Developer</span>
                                            </div>
                                            <a href="#" class="comment-reply"><i class="icofont-reply"></i> Reply</a>
                                        </div>
                                        <p>It is a long established fact that a reader will be distracted by the re he point of using Lorem Ipsum is that it has a more-or-less normal content here', making.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="blog-comment-form">
                                <h4>Leave A Comments</h4>
                                <div class="comment-form">
                                    <form action="#">
                                        <div class="form-row">
                                            <div class="col-12">
                                                <input type="text" class="form-control custom-input" id="name" name="name" value="" placeholder="Name:" required/>
                                            </div>
                                            <div class="col-12">
                                                <input type="email" class="form-control custom-input" id="email" name="email" value="" placeholder="Email:" required/>
                                            </div>
                                            <div class="col-12">
                                                <input type="text" class="form-control custom-input" id="number" name="number" value="" placeholder="Phone:" />
                                            </div>
                                            <div class="col-12">
                                                <textarea class="form-control custom-textarea" id="message:" name="message:" rows="6" placeholder="Message:" required></textarea>
                                            </div>
                                        </div>
                                        <div class="text-center col-12">
                                            <button type="submit" class="btn submit">Submit Comment <i class="icofont-arrow-right"></i></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Blog Details Content -->

        <!-- START Call To Action -->
        <section class="cta-section pb-120 rpb-100 bg-white">
            <div class="container">
                <div class="contact-withus">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="contact-withus-content">
                                <h3>Contact With Us.<br /> To Require a Detailed Analysis of Your Plan.</h3>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div class="contact-withus-num">
                                <a class="contact-number" href="callto:0095788394">+00 95 788 394</a>
                                <a href="contact.html" class="btn theme-btn">Contact Today<i class="icofont-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Call To Action -->