
<?php
include _VIEW_PATH."/common_header.phtml";?>

	<?php
	// include _VIEW_PATH."/customer/profile_left_menu.phtml";
	include _VIEW_PATH."common_top_bar.phtml";
	// include _VIEW_PATH.$lib->lang."/top_menu.phtml";
	?>

	<?php
	include _VIEW_PATH.$lib->lang."/category_content.phtml";
	?>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>