<!-- Main Content-->
<div class="main-content side-content pt-0">

    <div class="container-fluid">
        <div class="inner-body">
                <!-- Page Header -->
                <div class="page-header">

					<div>
						<h2 class="main-content-title tx-24 mg-b-5">Catégories</h2>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a class="" href="#"><?= $url_array[1] ?></a></li>
							<li class="breadcrumb-item active" aria-current="page"><?= $url_array[2] ?></li>
						</ol>
					</div>
							
					<div class="d-flex">
						<div class="justify-content-center">
							<button onclick="document.location='<?php $lib->customerSite ?>/configurations/categories/ajouter'" type="button" class="btn btn-primary my-2 btn-icon-text">
								<i class="fas fa-plus mr-2"></i> Ajouter une nouvelle catégorie
							</button>
						</div>
					</div>

                </div>
                <!-- End Page Header -->

                <!-- Row -->
                <div class="row row-sm">
                    <div class="col-lg-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div>
									<h6 class="main-content-label mb-1">Liste des Catégories</h6>
								</div>
                                <div class="table-responsive">
                                    <table id="example2" class="table table-bordered text-nowrap" >
                                    <thead>
										<tr>
                                            <th>Libellé de la catégorie</th>
                                            <th>Type de la catégorie</th>
                                            <th>Actions</th>
										</tr>
									</thead>
											<tbody>
                                                <?php if(!empty($data['categories'])):?>
                                                    <?php foreach($data['categories'] as $category):?>
                                                        <tr>
                                                            <td><?= $category['libelle'] ?></td>
                                                            <td><?= $category['type_category_libelle'] ?></td>                                                          
                                                            <td >
                                                                <span onclick="document.location='<?php $lib->customerSite ?>/configurations/categories/modifier/<?=$category['category_id'] ?>'" class="btn ripple btn-info">Modifier</span>
                                                            </td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                <?php endif;?>
                                            </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->    
        </div>
    </div>
</div>
<!-- End Main Content-->