<?php if ($iniObj->debugViews) echo __FILE__; ?>

<!-- Footer -->
<footer class="g-bg-main-light-v1">
  <!-- Content -->
  <div class="g-brd-bottom g-brd-secondary-light-v1">
    <div class="container g-pt-100">
      <div class="row justify-content-start g-mb-30 g-mb-0--md">
        <div class="col-md-3 g-mb-30">
          <h2 class="h5 g-color-gray-light-v3 mb-4">Les espaces produits</h2>

          <div class="row">
            <div class="col-4 g-mb-20">
              <!-- Links -->
              <ul class="list-unstyled g-font-size-13 mb-0">
                <li class="g-mb-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_CULTLOISIR_Culture_Loisirs_Sport">Culture / Loisirs / Sport</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_DECO_Décoration">Décoration</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_DIVERS_Divers">Divers</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_ELECTROMEN_Electroménager">Electroménager</a>
                </li>
              </ul>
              <!-- End Links -->
            </div>

            <div class="col-4 g-mb-20">
              <!-- Links -->
              <ul class="list-unstyled g-font-size-13 mb-0">
                <li class="g-mb-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_EQUIPERSON_Equipement_de_la_personne">Equipement de la personne</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_INFOJVIDEO_Informatique_Jeux_vidéo">Informatique / Jeux vidéo</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_JAROUTANIM_Bricolage_Jardinage_Animalerie">Bricolage / Jardinage / Animalerie</a>
                </li>
              </ul>
              <!-- End Links -->
            </div>

            <div class="col-4 g-mb-20">
              <!-- Links -->
              <ul class="list-unstyled g-font-size-13 mb-0">
                <li class="g-mb-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_MEUBLES_Meubles">Meubles</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_TVSONMUL_Son_Image_Téléphonie">Son / Image / Téléphonie</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_VEHICULE_Véhicules">Véhicules</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/espace_LITERIE_Literie">Literie</a>
                </li>
              </ul>
              <!-- End Links -->
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4 g-mb-30 g-mb-0--sm">
          <h2 class="h5 g-color-gray-light-v3 mb-4">Liens utiles</h2>

          <div class="row">
            <div class="col-6 g-mb-20">
              <!-- Links -->
              <ul class="list-unstyled g-font-size-13 mb-0">
                <li class="g-mb-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="#">Nos catégories</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="#">Prix en baisse</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="#">Espace déposant</a>
                </li>
              </ul>
              <!-- End Links -->
            </div>

            <div class="col-6 g-mb-20">
              <!-- Links -->
              <ul class="list-unstyled g-font-size-13 mb-0">
                <li class="g-mb-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="#">Support</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="#">FAQ</a>
                </li>
                <li class="g-my-10">
                  <a class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover" href="/customer/login/<?= $lib->random(); ?>">Se connecter</a>
                </li>
              </ul>
              <!-- End Links -->
            </div>
          </div>
        </div>

        <div class="col-sm-5 col-md-3 ml-auto g-mb-30 g-mb-0--sm">
          <h2 class="h5 g-color-gray-light-v3 mb-4">Contacts</h2>

          <!-- Links -->
          <ul class="list-unstyled g-color-gray-dark-v5 g-font-size-13">
            <li class="media my-3">
              <i class="d-flex mt-1 mr-3 icon-hotel-restaurant-235 u-line-icon-pro"></i>
              <div class="media-body">
                Info adresse
                <br>
                Info adresse
              </div>
            </li>
            <li class="media my-3">
              <i class="d-flex mt-1 mr-3 icon-communication-062 u-line-icon-pro"></i>
              <div class="media-body">
                contact@jiscomputing.com
              </div>
            </li>
            <!-- <li class="media my-3">
              <i class="d-flex mt-1 mr-3 icon-communication-033 u-line-icon-pro"></i>
              <div class="media-body">
                +00 000 00 00 00
              </div>
            </li> -->
          </ul>
          <!-- End Links -->
        </div>
        <div class="col-md-2  g-mb-50 text-center">
          <img src="<?php echo $iniObj->logoPath; ?>" alt="Occaz et Neuf">
          <br>
           <p>OccazetNeuf est le 1er portail de vente de produits neufs et d'occasion par les professionnels de la vente.</p>
          
        </div>

      </div>

      <!-- Secondary Content -->
      <div class="row">


        <!-- <div class="col-md-3 g-mb-50">
          <h2 class="h5 g-color-gray-light-v3 mb-4">A propos</h2>
          <p>OccazetNeuf est le 1er portail de vente de produits neufs et d'occasion par les professionnels de la vente.</p> -->
        <!-- Subscribe Form 
                <form class="input-group u-shadow-v19 rounded">
                  <input class="form-control g-brd-none g-color-gray-dark-v5 g-bg-main-light-v2 g-bg-main-light-v2--focus g-placeholder-gray-dark-v3 rounded g-px-20 g-py-8" type="email" placeholder="Enter your email">
                  <span class="input-group-addon u-shadow-v19 g-brd-none g-bg-main-light-v2 g-pa-5">
                    <button class="btn u-btn-primary rounded text-uppercase g-py-8 g-px-18" type="submit">
                      <i class="fa fa-angle-right"></i>
                    </button>
                  </span>
                </form>
                
                End Subscribe Form -->
        <!-- </div> -->

        <div class="col-6 col-md-3 ml-auto g-mb-30">
          <!-- <h2 class="h5 g-color-gray-light-v3 mb-4">Follow Us On:</h2> -->

          <!-- Social Icons -->
          <!-- <ul class="list-inline mb-50">
                  <li class="list-inline-item g-mr-2">
                    <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-facebook--hover rounded" href="#">
                      <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fa fa-facebook"></i>
                      <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fa fa-facebook"></i>
                    </a>
                  </li>
                  <li class="list-inline-item g-mx-2">
                    <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-twitter--hover rounded" href="#">
                      <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fa fa-twitter"></i>
                      <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fa fa-twitter"></i>
                    </a>
                  </li>
                  <li class="list-inline-item g-mx-2">
                    <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-instagram--hover rounded" href="#">
                      <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fa fa-instagram"></i>
                      <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fa fa-instagram"></i>
                    </a>
                  </li>
                  <li class="list-inline-item g-mx-2">
                    <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-google-plus--hover rounded" href="#">
                      <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fa fa-google-plus"></i>
                      <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fa fa-google-plus"></i>
                    </a>
                  </li>
                  <li class="list-inline-item g-mx-2">
                    <a class="u-icon-v1 u-icon-slide-up--hover g-color-gray-dark-v4 g-color-white--hover g-bg-linkedin--hover rounded" href="#">
                      <i class="g-font-size-18 g-line-height-1 u-icon__elem-regular fa fa-linkedin"></i>
                      <i class="g-color-white g-font-size-18 g-line-height-0_8 u-icon__elem-hover fa fa-linkedin"></i>
                    </a>
                  </li>
                </ul> -->
          <!-- End Social Icons -->
        </div>
      </div>
      <!-- End Secondary Content -->
    </div>
  </div>
  <!-- End Content -->

  <!-- Copyright -->
  <div class="container g-pt-30 g-pb-10">
    <div class="row justify-content-between align-items-center">
      <div class="col-md-4 g-mb-20">
        <p class="g-font-size-13 mb-0">2020 &copy; JIS Computing. Tous droits réservés.</p>
      </div>
      <div class="col-md-4 g-mb-20">
        <p class="g-font-size-13 mb-0">
          <a href="/mentionslegales/<?= $random ?>">Mentions légales</a> |
          <a href="#cookienotice">Gestion des cookies</a> |
          <a href="/cgu/<?= $random ?>">CGU</a>
        </p>
      </div>

      <div class="col-md-4 text-md-right g-mb-20">
        <ul class="list-inline g-color-gray-dark-v5 g-font-size-25 mb-0">
          <!-- <li class="list-inline-item g-cursor-pointer mr-1">
            <i class="fa fa-cc-visa" title="Visa" data-toggle="tooltip" data-placement="top"></i>
          </li>
          <li class="list-inline-item g-cursor-pointer mx-1">
            <i class="fa fa-cc-paypal" title="Paypal" data-toggle="tooltip" data-placement="top"></i>
          </li>
          <li class="list-inline-item g-cursor-pointer mx-1">
            <i class="fa fa-cc-mastercard" title="Master Card" data-toggle="tooltip" data-placement="top"></i>
          </li>
          <li class="list-inline-item g-cursor-pointer ml-1">
            <i class="fa fa-cc-stripe" title="Stripe" data-toggle="tooltip" data-placement="top"></i>
          </li>
          <li class="list-inline-item g-cursor-pointer ml-1">
            <i class="fa fa-cc-discover" title="Discover" data-toggle="tooltip" data-placement="top"></i>
          </li>
          <li class="list-inline-item g-cursor-pointer ml-1">
            <i class="fa fa-cc-jcb" title="JCB" data-toggle="tooltip" data-placement="top"></i>
          </li> -->
        </ul>
      </div>
    </div>
  </div>
  <!-- End Copyright -->
</footer>
<!-- End Footer -->