
			<!-- Main Content-->
			<div class="main-content side-content pt-0">

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
                                <div>
                                    <h2 class="main-content-title tx-24 mg-b-5">Marchands</h2>
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#"><?= $url_array[1] ?></a></li>
                                        <li class="breadcrumb-item active" aria-current="page"><?= $url_array[2] ?></li>
                                    </ol>
                                </div>
                                        
                                <div class="d-flex">
                                    <div class="justify-content-center">
                                        <button onclick="document.location='<?php $lib->customerSite ?>/administration/agent/ajouter'" type="button" class="btn btn-primary my-2 btn-icon-text">
                                            <i class="fas fa-plus mr-2"></i> Ajouter une nouveau marchand
                                        </button>
                                    </div>
                                </div>
							</div>
							</div>
						</div>
						<!-- End Page Header -->

						<!-- Row -->
						<div class="row row-sm">
							<div class="col-lg-12">
								<div class="card custom-card">
									<div class="card-body">
										<div>
											<h6 class="main-content-label mb-1">Liste des marchands</h6>
										</div>
										<div class="table-responsive">
											<table class="table" id="example2">
                                            <thead>
                                                <tr>
                                                    <th>Nom de la compagnie</th>
                                                    <th>RCCM</th>
                                                    <th>N°IFU</th>
                                                    <th>Token</th>
                                                    <th style="text-align:center">Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php if(!empty($data['compagnies'])):?>
                                                    <?php foreach($data['compagnies'] as $compagnie):?>
                                                        <tr>
                                                            <td><?= $compagnie['company_name'] ?></td>
                                                            <td><?= $compagnie['company_number'] ?></td>
                                                            <td><?= $compagnie['registration_number'] ?></td>
                                                            <td><?= $compagnie['company_token'] ?></td>
                                                            <td>
                                                                <span class="btn btn-primary my-2" onclick="document.location='<?php $lib->customerSite ?>/marchands/modifier/<?=$compagnie['company_id'] ?>'">Modifier</span>
                                                            </td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                <?php endif;?>
                                            </tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- End Row -->



