<!DOCTYPE html>
<html lang="en">


<head>
	<meta charset="utf-8">
	<title>GEMO - Gestion des Marchands Opérateurs</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<meta name="keywords" content="gemo">
	<meta name="description" content="GEMO - Gestion des Marchands Opérateurs">
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&amp;display=swap" rel="stylesheet">
	<!-- Favicon -->
	<link rel="icon" type="image/png" href="<?php echo $iniObj->UIPath; ?>/img/favicon.png">
	
	<!-- Bootstrap Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/bootstrap.min.css">
	<!-- Font Awesome Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/font-awesome.min.css">
	<!-- IcoFont Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/icofont.min.css">
	<!-- IcoMoon Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/themify-icons.css">
	<!-- Magnific Popup Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/magnific-popup.css">
	<!-- Owl Carousel Min CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/owl.carousel.min.css">
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/owl.theme.default.min.css">
	<!-- Site Main Style sheet css -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/styles.css">
	<!-- Site Main Responsive CSS -->
	<link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/assets/css/responsive.css">
</head>

<body>

	<!-- Start Preloader Area -->
    <div id="loader">
        <div class="spinner">
            <div class="dot1"></div>
            <div class="dot2"></div>
        </div>
    </div>
	<!-- End Preloader Area -->
	
	<!-- Start Navbar Area-->
	<nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top navbar-reduce" id="mainNav">
		<div class="container"> <a class="navbar-brand js-scroll" href="">
			<div style="width:150px" id="black">
				<img src="<?php echo $iniObj->UIPath; ?>/logo" alt="Logo GEMO" srcset="">
			</div>
			 </a>
			<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation"> <span></span>
				<span></span>
				<span></span>
			</button>
			<div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
				<ul class="navbar-nav">
				
					<li class="nav-item"> <a class="nav-link js-scroll active" href="/">Accueil</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="#features">Fonctionnalités</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="#about">Présentation</a>
					</li>
					
					<li class="nav-item"> <a class="nav-link js-scroll" href="#download">Téléchargement</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll" href="#contact">Contact</a>
					</li>
					<li class="nav-item"> <a class="nav-link js-scroll btn btn-warning rounded-pill" href="<?php $lib->customerSite ?>/connecter">connexion</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!-- End Navbar Area -->

	<!-- Start Contact Section -->
	<section id="contact" class="contact-area section-padding" style="padding: 200px 0;">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-title">
						<h6 class="small-title">Rendez-vous</h6>
						<h2>Prenez un rendez-vous</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-5 col-md-12">
					<div class="contact-information-box-3">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12">
								<div class="single-contact-info-box">
									<div class="contact-info">	<i class="icofont-location-pin"></i>
										<h6>Address:</h6>
										<p>526 Melrose Street,</p>
										<p>Water Mill, 11976 New York.</p>
									</div>
									<div class="contact-info-bg-icon">	<i class="icofont-location-pin"></i>
									</div>
								</div>
							</div>
							<div class="col-lg-12 col-md-12 col-sm-12">
								<div class="single-contact-info-box">
									<div class="contact-info">	<i class="icofont-phone-circle"></i>
										<h6>Phone:</h6>
										<p>+080 707 555-321</p>
										<p>+105 773 321 7775</p>
									</div>
									<div class="contact-info-bg-icon">	<i class="icofont-phone-circle"></i>
									</div>
								</div>
							</div>
							<div class="col-lg-12 col-md-12 col-sm-12">
								<div class="single-contact-info-box">
									<div class="contact-info">	<i class="icofont-email"></i>
										<h6>Email:</h6>
										<p>commercial@gemo.app</p>
										<p>support@example.com</p>
									</div>
									<div class="contact-info-bg-icon">	<i class="icofont-email"></i>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-7 col-md-12">
					<p class="form-message"></p>
					<div class="contact-form-box">
						<form class="contact-form form" id="contact-form" action="" method="POST">
							<div class="controls">
								<div class="row">
									<div class="col-lg-12 col-md-12">
										<div class="form-group has-error has-danger">
											<input id="form_name" type="text" name="name" placeholder="Vôtre nom" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-12">
										<div class="form-group has-error has-danger">
											<input id="form_email" type="text" name="phone" placeholder="Vôtre contact" required="required">
										</div>
									</div>
									<div class="col-lg-6 col-md-12">
										<div class="form-group has-error has-danger">
											<input id="form_subject" type="text" name="subject" placeholder="Vôtre sujet de message" required="required">
										</div>
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<textarea id="form_message" name="message" placeholder="Vôtre message" rows="4" required="required"></textarea>
										</div>
									</div>
									<div class="col-md-12">
										<button type="submit" class="button">Envoyer le Message</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Contact Section -->
	
	<!-- Start Footer Section -->
	<footer class="footer-area">
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 130">
			<path fill="#fff" fill-opacity="1" d="M0,64L48,64C96,64,192,64,288,53.3C384,43,480,21,576,37.3C672,53,768,107,864,117.3C960,128,1056,96,1152,80C1248,64,1344,64,1392,64L1440,64L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
		</svg>
		<div class="footer-top-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 offset-lg-2 col-md-12 text-center">
						<div class="footer-logo-box">
							<h2>GEMO</h2>
							<p>GEMO ,la solution qui simplifie la vie des marchands GSM. Ne perdez plus de temps rejoignez la communauté GEMO.</p>
						</div>
						<div class="footer-social-icon">
							<a href="#" class="icon"> <i class="fa fa-facebook"></i> 
							</a>
							<a href="#" class="icon"> <i class="fa fa-twitter"></i> 
							</a>
							<a href="#" class="icon"> <i class="fa fa-instagram"></i> 
							</a>
							
						</div>
						
					</div>
				</div>
			</div>
		</div>
		<div class="copyright-area text-center">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p>Copyright &copy; 2021 - All Right Reserved.</p>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- End Footer Section -->
	
	<!-- Back to Top -->
	<a href="#" class="back-to-top back-to-top-pulse"><i class="fa fa-caret-up"></i></a>
	
	<!-- Start Live Chat Code -->
	<script type="text/javascript" src="http://localhost/live_chat/assets/js/jquery.min.js"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<script type="text/javascript">jQuery(document).ready(function($) {$.ajaxSetup({xhrFields: {withCredentials: true},headers: {"X-Requested-With": "XMLHttpRequest"}});$.ajax({type: "GET",url: "http://localhost/live_chat/live_chat",dataType: "html",success: function(data) {$("body").append(data);}});});</script>
	<!-- End Live Chat Code -->
	<!-- All Jquery Js-->
	<script src="<?php echo $iniObj->UIPath; ?>/js/jquery-3.5.1.min.js"></script>
	<script src="<?php echo $iniObj->UIPath; ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $iniObj->UIPath; ?>/js/plugins.js"></script>
	<!--Site Main js-->
	<<script>
   
        $(window).on('load', function () {
        $('#loader').fadeOut('slow', function () {
            $(this).remove();
        });
		
    });
    
    </script>
	
</body>


</html>