<!-- Main Content-->
<div class="main-content side-content pt-0">

<div class="container-fluid">
    <div class="inner-body">

        <?php if(!empty($_SESSION['notification'])):?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
        <?=$_SESSION['notification']?>
        <?php endif; ?>

            <!-- Page Header -->
            <div class="page-header">

                <?php include _VIEW_PATH."common_top_for_dashboard_content.phtml"; ?>

            </div>
            <!-- End Page Header -->

            <div class="card-filter">
        <form class="row g-3" action="" method="post">
            <div class="col-md-4">
                <?php if($_SESSION['access'] == '1'):?>
                    <label for="marchand" class="form-label">Marchands</label>
                    
                
                    <select id="marchand" name="marchand" class="form-control select2">
                        <option selected>Séléctionner un marchand</option>
                        <?php if(isset($data['marchand'])): ?>
                            <?php foreach($data['marchand'] as $marchand): ?>
                                <option value="<?=$marchand['application_uuid'] ?>"><?=$marchand['firstname'] ?> <?=$marchand['lastname'] ?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                <?php else :?>
                    <?php if($_SESSION['access'] == '2'):?>
                        <label for="manager" class="form-label">Manager</label>
                        <select id="manager" name="manager" class="form-select">
                            <option selected>Séléctionner un manager</option>
                            <?php if(isset($data['marchand'])): ?>
                                <?php foreach($data['marchand'] as $marchand): ?>
                                    <option value="<?=$marchand['company_id'] ?>"><?=$marchand['firstname'] ?> <?=$marchand['lastname'] ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    <?php endif;?>
                <?php endif;?>
            </div>
            <div class="col-md-4">
                <label for="debut" class="form-label">Date début</label>
                <input type="date" name="debut" class="form-control" id="debut">
            </div>
            <div class="col-md-4">
                <label for="inputZip" class="form-label">Date fin</label>
                <input type="date" name="fin" class="form-control" id="inputZip">
            </div>
            <div class="col-12 mt-2">
                <button type="submit" name="filter" class="btn btn-primary">Filtrer</button>
            </div>
        </form>
        </div>

            <!-- Row -->
            <div class="row row-sm mt-5">
                <div class="col-lg-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div>
                                <h6 class="main-content-label mb-1">Liste des opérations</h6>
                                <!-- <p class="text-muted card-sub-title">Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.</p> -->
                            </div>
                            <div class="table-responsive">

                            <?php if($_SESSION['access'] == '1'):?>
                                <table id="exportexample" class="table table-striped table-bordered text-nowrap" >

                                    <thead>
                                        <tr>
                                            <th>Types</th>
                                            <th>Descriptions</th>
                                            <th>Dates</th>
                                            <th>Gsm</th>
                                            
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(isset($data['operations'])): ?>
                                            <?php foreach($data['operations'] as $opération): ?>
                                            <tr>
                                                <td><?=$opération['libelle'] ?></td>
                                                <td><?=$opération['operation_date'] ?></td>                                             
                                                <td><?=$opération['description'] ?></td>
                                                <td><?=$opération['network_operator_name'] ?></td>
                                            </tr>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            <?php else :?>
                                    <?php if($_SESSION['access'] == '2'):?>
                                        <table id="tables" class="table table-striped" style="margin-top: 30px;" border="0">
                                    <thead>
                                        <tr>
                                            <th>Types</th>
                                            
                                            <th>Dates</th>
                                            <th>Montant</th>
                                            <th>Gsm</th>
                                            <th>Agent</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(isset($data['operations'])): ?>
                                            <?php foreach($data['operations'] as $opération): ?>
                                            <tr>
                                                <td><?=$opération['libelle'] ?></td>
                                                <td><?=$opération['operation_date'] ?></td>                                             
                                                <td><?=$opération['amount'] ?> FCFA</td>
                                                <td><?=$opération['network_operator_name'] ?></td>
                                                <td><?=$opération['firstname'] ?> <?=$opération['lastname'] ?></td>
                                                
                                            </tr>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                                <?php endif;?>
                            <?php endif;?>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Row -->    
    </div>
</div>
</div>
<!-- End Main Content-->