<?php if($iniObj->debugViews) echo __FILE__ ; ?>

    <!-- News -->
    <!-- <div class="container g-pt-10 g-pb-30">
        <div class="text-center mx-auto g-max-width-600 g-mb-20">
          <h1 class="g-color-black mb-4 title-uppercase">Actualités OccazetNeuf</h1>
        </div> -->

        <!-- <div class="row g-mx-minus-10">
          <div class="col-sm-6 col-md-4 g-px-10 g-mb-30"> -->
            <!-- Blog Background Overlay Blocks -->
            <!-- <article class="u-block-hover">
              <div class="g-bg-cover g-bg-white-gradient-opacity-v1--after">
                <img class="d-flex align-items-end u-block-hover__main--mover-down" src="<?php echo $iniObj->imgNewsPath; ?>/news1.jpg" alt="Image Description">
              </div>
              <div class="u-block-hover__additional--partially-slide-up text-center g-z-index-1 mt-auto">
                <div class="u-block-hover__visible g-pa-25">
                  <span class="d-block g-color-white-opacity-0_7 g-font-size-13 mb-2">CATEGORIE</span>
                  <h2 class="h4 g-color-white g-font-weight-400 mb-3">
                    <a class="u-link-v5 g-color-white g-color-primary--hover g-cursor-pointer" href="#">Titre de l'article ici</a>
                  </h2>
                  <h4 class="d-inline-block g-color-white-opacity-0_7 g-font-size-11 mb-0">
                    Auteur : 
                    <a class="g-color-white-opacity-0_7 text-uppercase" href="#">Nom de l'auteur</a>
                  </h4>
                  <span class="g-color-white-opacity-0_7 g-pos-rel g-top-2 mx-2">&#183;</span>
                  <span class="g-color-white-opacity-0_7 g-font-size-10 text-uppercase">Insérer la date ici</span>
                </div>

                <a class="d-inline-block g-brd-bottom g-brd-white g-color-white g-font-weight-500 g-font-size-12 text-uppercase g-text-underline--none--hover g-mb-30" href="#">En savoir plus</a>
              </div>
            </article> -->
            <!-- End Blog Background Overlay Blocks -->
          <!-- </div>

          <div class="col-sm-6 col-md-4 g-px-10 g-mb-30"> -->
            <!-- Blog Background Overlay Blocks -->
            <!-- <article class="u-block-hover">
              <div class="g-bg-cover g-bg-white-gradient-opacity-v1--after">
                <img class="d-flex align-items-end u-block-hover__main--mover-down" src="<?php echo $iniObj->imgNewsPath; ?>/news2.jpg" alt="Image Description">
              </div>
              <div class="u-block-hover__additional--partially-slide-up text-center g-z-index-1 mt-auto">
                <div class="u-block-hover__visible g-pa-25">
                  <span class="d-block g-color-white-opacity-0_7 g-font-size-13 mb-2">CATEGORIE</span>
                  <h2 class="h4 g-color-white g-font-weight-400 mb-3">
                    <a class="u-link-v5 g-color-white g-color-primary--hover g-cursor-pointer" href="#">Titre de l'article ici</a>
                  </h2>
                  <h4 class="d-inline-block g-color-white-opacity-0_7 g-font-size-11 mb-0">
                    Auteur : 
                    <a class="g-color-white-opacity-0_7 text-uppercase" href="#">Nom de l'auteur</a>
                  </h4>
                  <span class="g-color-white-opacity-0_7 g-pos-rel g-top-2 mx-2">&#183;</span>
                  <span class="g-color-white-opacity-0_7 g-font-size-10 text-uppercase">Insérer la date ici</span>
                </div>

                <a class="d-inline-block g-brd-bottom g-brd-white g-color-white g-font-weight-500 g-font-size-12 text-uppercase g-text-underline--none--hover g-mb-30" href="#">En savoir plus</a>
              </div>
            </article> -->
            <!-- End Blog Background Overlay Blocks -->
          <!-- </div> -->


          <!-- <div class="col-sm-6 col-md-4 g-px-10 g-mb-30"> -->
            <!-- Blog Background Overlay Blocks -->
            <!-- <article class="u-block-hover">
              <div class="g-bg-cover g-bg-white-gradient-opacity-v1--after">
                <img class="d-flex align-items-end u-block-hover__main--mover-down" src="<?php echo $iniObj->imgNewsPath; ?>/news3.jpg" alt="Image Description">
              </div>
              <div class="u-block-hover__additional--partially-slide-up text-center g-z-index-1 mt-auto">
                <div class="u-block-hover__visible g-pa-25">
                  <span class="d-block g-color-white-opacity-0_7 g-font-size-13 mb-2">CATEGORIE</span>
                  <h2 class="h4 g-color-white g-font-weight-400 mb-3">
                    <a class="u-link-v5 g-color-white g-color-primary--hover g-cursor-pointer" href="#">Titre de l'article ici</a>
                  </h2>
                  <h4 class="d-inline-block g-color-white-opacity-0_7 g-font-size-11 mb-0">
                    Auteur : 
                    <a class="g-color-white-opacity-0_7 text-uppercase" href="#">Nom de l'auteur</a>
                  </h4>
                  <span class="g-color-white-opacity-0_7 g-pos-rel g-top-2 mx-2">&#183;</span>
                  <span class="g-color-white-opacity-0_7 g-font-size-10 text-uppercase">Insérer la date ici</span>
                </div>

                <a class="d-inline-block g-brd-bottom g-brd-white g-color-white g-font-weight-500 g-font-size-12 text-uppercase g-text-underline--none--hover g-mb-30" href="#">En savoir plus</a>
              </div>
            </article> -->
            <!-- End Blog Background Overlay Blocks -->
          <!-- </div>

        </div>
      </div> -->
      <!-- End News -->