<!-- Main Content-->
<div class="main-content side-content pt-0">

    <div class="container-fluid">
        <div class="inner-body">

            <?php if(!empty($_SESSION['notification'])):?>
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
            <?=$_SESSION['notification']?>
            <?php endif; ?>

                <!-- Page Header -->
                <div class="page-header">

                    <?php include _VIEW_PATH."common_top_for_dashboard_content.phtml"; ?>

                </div>
                <!-- End Page Header -->

                <!-- Row -->
                <div class="row row-sm">
                    <div class="col-lg-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div>
                                    <h6 class="main-content-label mb-1">Vertical Scrollable Data Table</h6>
                                    <p class="text-muted card-sub-title">Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.</p>
                                </div>
                                <div class="table-responsive">
                                    <table id="example3" class="table table-striped table-bordered text-nowrap" >
                                    <thead>
                                    <tr>
                                        <th>Nom de l'inventaire</th>
                                        <th>Date début </th>
                                        <th>Date fin</th>
                                        <th style="text-align:center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php if(isset($response)): ?>
                                        <?php foreach($response as $res): ?>
                                        <tr>
                                             <td><?=$res['inventory_name'] ?></td>
                                             <td><?=$res['date_from'] ?></td>
                                             <td><?=$res['date_to'] ?></td>           
                                             <td style="text-align:center"> 
                                               
                                                <span onclick="document.location='<?php $lib->customerSite ?>/administration/inventaire/details/<?=$res['inventory_id'] ?>/<?=$res['inventory_name'] ?>'" class="btn ripple btn-info">Details</span>
                                             </td>
                                            
                                        </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->    
        </div>
    </div>
</div>
<!-- End Main Content-->