
			<!-- Main Content-->
			<div class="main-content side-content pt-0">

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
							<div>
								<h2 class="main-content-title tx-24 mg-b-5">Licences</h2>
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#">Licences</a></li>
									
								</ol>
                                <div class="d-flex">
								<div class="justify-content-center">
									
									<button type="button" class="btn btn-info my-2 btn-lg">
                                    Ajouter une nouvelle licence
									</button>
								</div>
							</div>
							</div>
						</div>
						<!-- End Page Header -->

						
                        

						<!-- Row -->
						<div class="row row-sm">
							<div class="col-lg-12">
								<div class="card custom-card">
									<div class="card-body">
										<div>
											<h6 class="main-content-label mb-1">Liste des licences</h6>
										</div>
										<div class="table-responsive">
											<table class="table" id="example2">
												<thead>
													<tr>
                                                        <th class="wd-20p">Licence key</th>
                                                        <th class="wd-20p">Société</th>
                                                        <th class="wd-20p">Type</th>
                                                        <th class="wd-20p">Date d'expiration</th>
                                                        <th>Statut</th>
                                                        <th class="wd-20p">Actions</th>
													</tr>
												</thead>
												<tbody>
                                                <?php if(isset($data['licences'])): ?>
                                                    <?php foreach($data['licences'] as $licence): ?>
                                                    <tr>
                                                        <td><?=$licence['licence_key'] ?></td>
                                                        <td><?=$licence['company_name'] ?></td>
                                                        <td><?=$licence['licence_type_name'] ?></td>
                                                        <td><?=$licence['expiration_date'] ?></td>
                                                        <td>
                                                            <?php if($licence['is_active'] == 1): ?>
                                                                <span class="badge badge-pill badge-success">Activer</span>
                                                            <?php endif; ?>
                                                            <?php if($licence['is_active'] == 0): ?>
                                                                <span class="badge badge-pill badge-danger">Bloquer</span>
                                                            <?php endif; ?>
                                                            <!--<?php //if($licence['is_active'] == 2): ?>
                                                                <span class="span-success danger">Revoquer</span>
                                                            <?php //endif; ?>-->
                                                        </td>
                                                        
                                                        <td>
                                                            <!--<span onclick="document.location='<?php $lib->customerSite ?>/licences/activer/<?=$licence['licence_id'] ?>'" class="btn-action white pg-5 success cursor"> Offres</span>-->
                                                            <button onclick="document.location='<?php $lib->customerSite ?>/licences/bloquer/<?=$licence['licence_id'] ?>'" class="btn ripple btn-danger">Bloquer</button>
                                                            <!--<span onclick="document.location='<?php $lib->customerSite ?>/licences/modifier/<?=$licence['licence_id'] ?>'" class="btn-action white pg-5 primary cursor">Relancer</span>-->
                                                            <button onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/<?=$licence['licence_id'] ?>'" class="btn ripple btn-info">Sous-Licences</button>
                                                        </td>
                                                    </tr>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- End Row -->

						