<?php
 if($iniObj->debugViews) echo __FILE__ ;
$carouselActive = false;
$sliderActive=true;
$title = $storeDetail->storeName." - Articles neufs et occasions - Professionnel - Dépôt vente - Electroménager - Décoration - Informatique - Jeux vidéo - Son - Image - Téléphonie - Bricolage - Jardinage - Animalerie";

	include _VIEW_PATH."/common_header.phtml";?>

	<?php
		if($storeActive==1){
			include _VIEW_PATH.$lib->lang."/top_menu_magasin.phtml";
		}
		else{
			include _VIEW_PATH.$lib->lang."/top_menu.phtml";
		}
	?>
	
	<!-- Breadcrumbs -->
	<section class="g-brd-bottom g-brd-gray-light-v4 g-py-30" style="background-image: url('<?php 
		if(($storeImage->storeHeaderImage)&&($storeImage->storeHeaderImageStatus)){echo $iniObj->imgHeaderPath.$storeImage->storeHeaderImage;}
		else{echo $iniObj->imgHeaderPath.$iniObj->defaultStoreHeaderImage;}
	?>');">
		<div class="container">
		<span class="page-name">Magasin</span>
			<h1>
				<?php echo $storeDetail->storeName;?>
			</h1>
		<ul class="u-list-inline">
			<li class="list-inline-item g-mr-5">
			<a href="/" class="u-link-v5 g-color-text">
				Accueil
				</a>
			<i class="g-color-gray-light-v2 g-ml-5 fa fa-angle-right"></i>
			</li>
			<li class="list-inline-item g-color-primary active">
				<span>Magasin <?php echo $storeDetail->storeName;?></span>
			</li>
		</ul>
		</div>
	</section>
	<!-- End Breadcrumbs -->

	<div class="container">
			
		<div class="row">
			
			<?php
				include _VIEW_PATH.$lib->lang."/magasin_left_menu.phtml";
			?>
			
			<?php
				if($promoActive){
					include _VIEW_PATH.$lib->lang."/magasin_prix_en_baisse_page_content.phtml";
				}
				else if($viewProductDetail==1){
					include _VIEW_PATH.$lib->lang."/magasin_product_detail.phtml";
				}else {
					include _VIEW_PATH.$lib->lang."/magasin_product_content.phtml";
				}
			?>
	</div>
	<!--/end row-->
	</div>
	<!--/end container-->

	<?php if($storeActive==1){
		include _VIEW_PATH.$lib->lang."/common_footer_magasin.phtml";
	}
	else{
		include _VIEW_PATH.$lib->lang."/common_footer.phtml";
	}

	include _VIEW_PATH."/common_include_files.phtml";?>
</div>
