<?php if($iniObj->debugViews) echo __FILE__ ; ?>


<div class="col-md-9 order-md-2">
        <div class="g-pl-15--lg">
			<?php
				include _VIEW_PATH.$lib->lang."/search_bar_magasin.phtml";
			?>
			<div class="row g-mt-20">
				<div class="col-lg-4 text-left">
					<h3 class="badge-results">
					<?php if(!empty($subCategoryId)) {
							echo $subCategory->subCategoryDescription;
							if ($nbResult->total>0) {
								if($nbResult->total >1) echo " (".$nbResult->total. " articles)"; else echo " (".$nbResult->total. " article)";;
							}
						}
						else if (!empty($categoryId)) {
							echo $category->description;
							if ($nbResult->total>0) {
								if($nbResult->total >1) echo " (".$nbResult->total. " articles)"; else echo " (".$nbResult->total. " article)";
							}
						}
						else {
							if($nbResult->total >1) echo " (".$nbResult->total. " articles)"; else echo " (".$nbResult->total. " article)";
						}

						?>
					</h3>
				</div>

				<div class="col-lg-8 text-right">
					<h3 class="title-uppercase"><?php echo $storeDetail->storeName;?></h3>
				</div>
			</div>
			
			<?php if($nbResult->total>0) { ?>
			<!--=== List resultats p ===-->
			<div class="row  g-pt-10 g-mb-20 ">
				<?php foreach($products['data'] as $k=>$v) {
				if(file_exists(realpath(_WEB_FILES.$iniObj->imgPath.$v->photo1))){
				?>

				<div class="col-6 col-lg-4 g-mb-30">
					<?php include _VIEW_PATH.$lib->lang."/product_card_component.phtml"; ?>
				</div>
				<?php }
			} ?>
			</div>
			<?php }
			 else{ ?>
				<div class="container text-center g-py-100">
					<div class="mb-5">
					<span class="d-block g-color-gray-light-v1 g-font-size-70 g-font-size-90--md mb-4">
						<i class="icon-science-032 u-line-icon-pro"></i>
					</span>
					<h2 class="g-mb-30">Aucun résultat trouvé pour votre recherche</h2>
					</div>
				</div>
			<?php } ?>

			<div class="row">
				<div class="col-lg-12">
					<!--=== pagination===-->
					<div class="text-center">
						<ul class="pagination pagination-v2">
							<?php
							$pagination->paginate($pages_requested,$currentPage);
							?>
						</ul>
					</div>
				</div>
				<!--/end pagination-->
			</div>
		</div>
	</div>

