<?php if($iniObj->debugViews) echo __FILE__ ; ?>

<div class="col-md-9 order-md-2">
	<div class="g-pl-15--lg">
		<!-- Breadcrumbs -->
		<section class="g-brd-bottom g-brd-gray-light-v4 g-py-20">
			<div class="container">
			<span class="page-name">Magasin <?php echo $storeDetail->storeName;?></span>
				<h1>
					<?php echo $product->subCategoryDescription;?>
				</h1>
				<ul class="u-list-inline">

					<li class="list-inline-item g-color-primary active">
						<span><?php echo str_replace("<br>","",$product->libelle);?></span>
					</li>
				</ul>
			</div>
		</section>
		<!-- End Breadcrumbs -->
	</div>
	<div class="row">
		<div class="col-12 col-lg-8">
			<!-- Carousel -->
			<div id="carouselCus1" class="js-carousel g-pt-10 g-mb-10"
					data-infinite="true"
					data-fade="true"
					data-arrows-classes="u-arrow-v1 g-brd-around g-brd-white g-absolute-centered--y g-width-45 g-height-45 g-font-size-14 g-color-white g-color-primary--hover rounded-circle"
					data-arrow-left-classes="fa fa-angle-left g-left-40"
					data-arrow-right-classes="fa fa-angle-right g-right-40"
					data-nav-for="#carouselCus2">
				<div class="js-slide g-bg-cover g-bg-black-opacity-0_1--after">
				<img class="img-fluid w-100" src="<?php echo $iniObj->imgPath.$product->photo1; ?>" alt="Image Description">
				</div>
				<div class="js-slide g-bg-cover g-bg-black-opacity-0_1--after">
				<img class="img-fluid w-100" src="<?php echo $iniObj->imgPath.$product->photo1; ?>" alt="Image Description">
				</div>
				<div class="js-slide g-bg-cover g-bg-black-opacity-0_1--after">
				<img class="img-fluid w-100" src="<?php echo $iniObj->imgPath.$product->photo1; ?>" alt="Image Description">
				</div>
			</div>

			<div id="carouselCus2" class="js-carousel text-center u-carousel-v3 g-mx-minus-5"
					data-infinite="true"
					data-center-mode="true"
					data-slides-show="3"
					data-is-thumbs="true"
					data-focus-on-select="false"
					data-nav-for="#carouselCus1">
				<div class="js-slide g-cursor-pointer g-px-5">
				<img class="img-fluid" src="<?php echo $iniObj->imgPath.$product->photo1; ?>" alt="Image Description">
				</div>

				<div class="js-slide g-cursor-pointer g-px-5">
				<img class="img-fluid" src="<?php echo $iniObj->imgPath.$product->photo1; ?>" alt="Image Description">
				</div>

				<div class="js-slide g-cursor-pointer g-px-5">
				<img class="img-fluid" src="<?php echo $iniObj->imgPath.$product->photo1; ?>" alt="Image Description">
				</div>
			</div>
			<!-- End Carousel -->
			</div>

			<div class="col-12 col-lg-4">
				<div class=" g-pt-70">
					<!-- Product Info -->
					<div class="g-mb-30">
					<h1 class="g-font-weight-300 mb-4"><?php echo $product->libelle;?></h1>
					<?php if(trim($product->description)) { ?>
					<p>
						<?php echo $product->description;?>
						<br>
					</p>
					<?php } ?>
				</div>
				<!-- End Product Info -->

				<!-- Price -->
				<div class="g-mb-30">
				<h2 class="g-color-gray-dark-v5 g-font-weight-400 g-font-size-12 text-uppercase mb-2">PRIX</h2>
				<span class="g-color-black g-font-weight-500 g-font-size-30 mr-2"><?php echo $product->currentPrice;?> &euro;</span>
				
				<?php if ($product->currentPrice < $product->initalPrice) { ?>
				<s class="g-color-gray-dark-v4 g-font-weight-500 g-font-size-16"><?php echo $product->initalPrice;?> &euro;</s>
				<?php }?>
				</div>
				<!-- End Price -->

				<div>
					
				<p class="wishlist-category">
					<strong>Quantité en stock : </strong>
					<?php echo $product->qteStock;?>
				</p>
				<p class="wishlist-category">
					<strong>Référence :</strong>
					<?php echo $product->webReference;?>


				</p>
				<p class="wishlist-category">
					<strong>Rayon :</strong> <a
						href="/rayon_<?php echo $product->subCategoryCode."_".$lib->cleanUrl($product->subCategoryDescription);
						?>"><?php echo $product->subCategoryDescription;?> </a>
				</p>
				<p class="wishlist-category">
					<strong>Magasin : </strong> <a
						href="/magasin_<?php echo $product->storeUrl;?>"><?php echo $product->storeName;?>
					</a>
				</p>
				<?php if($product->hauteur >0) { ?>
				<p class="wishlist-category">
					<strong>Hauteur : </strong>
					<?php echo $product->hauteur;?>
				</p>
				<?php } ?>
				<?php if($product->largeur >0) { ?>
				<p class="wishlist-category">
					<strong>Largeur : </strong>
					<?php echo $product->largeur;?>
				</p>
				<?php } ?>
				<?php if($product->profondeur >0) { ?>
				<p class="wishlist-category">
					<strong>Profondeur : </strong>
					<?php echo $product->profondeur;?>
				</p>
				<?php } ?>
				<p class="wishlist-category">
					<strong>Frais de port : </strong>
					<?php if($product->shippingPrice >0) echo $product->shippingPrice; else echo "Enlèvement magasin uniquement";?>
				</p>
				</div>

				<?php if(/*$iniObj->cartActive*/ 1==1){ ?>
					<!-- Buttons -->
					<div class="row g-mx-minus-5 g-mb-20 g-mt-20">
						<div class="offset-3"></div>
						<div class="col-6 g-px-5 g-mb-10 text-center">
						<button class="add-to-cart btn btn-block u-btn-primary g-font-size-12 text-uppercase g-py-15 g-px-25" type="button"
							data-productid="<?php echo $product->productId; ?>" data-productname="<?php echo $product->libelle; ?>" data-productimage="<?php echo $iniObj->imgPath . $product->photo1; ?>" data-productprice="<?php echo $product->currentPrice; ?>" data-productstorecode="<?php echo $product->storeCode; ?>" data-productstorename="<?php echo $product->storeName; ?>" data-productemailmagasin="<?php echo $product->email_magasin; ?>" data-productemaildirecteur="<?php echo $product->email_directeur; ?>" data-qtestock="<?= $product->qte_stock ?>"
							
						
							title="Ajouter au panier"
						>
							Ajouter au panier <i class="align-middle ml-2 icon-finance-100 u-line-icon-pro"></i>
						</button>
						</div>
					</div>
					<!-- End Buttons -->
				<?php } ?>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="g-mt-50 g-mb-30">
				<div class="sharethis-inline-share-buttons"></div>
			</div>
		</div>
	</div>

</div>
<!--=== End Shop Product ===-->


