<?php
$carouselActive = false;

include _VIEW_PATH . "/common_header.phtml"; ?>

<!-- Header -->
<?php include _VIEW_PATH."common_top_bar.phtml"; ?>
<!-- End Header -->
<section class="page-banners">
     <!--<div> <img class="img-banners" src="<?php echo $iniObj->UIPath; ?>/images/hero/banner-nos-services.jpg" alt="" srcset=""></div>-->
     <div class="container">
         <div class="banner-content text-center">
            <h2>Mentions légales</h2>
                <div class="page-breadcrumbs">
                    <nav aria-label="breadcrumbs">
                        <ol class="breadcrumbs breadcrumb">
                            <li class="breadcrumb-item"><a href="<?php $lib->customerSite ?>">Acceuil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Mentions légales</li>
                        </ol>
                    </nav>
                </div>
         </div>
     </div>
</section>
<div class="container g-py-40">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <!-- Blog Minimal Blocks -->
            <article class="g-mb-">
                <div class="g-mb-30">
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>1. Déclaration à l’APDP</B>
                        <br>Conformément à la loi 2017-20 portant code du numérique en République du 
                            Bénin (Livre 5ième relatif à la protection des données personnelles et de la vie 
                            privée), le site a fait l’objet d’une déclaration auprès de l’Autorité de Protection des 
                            Données Personnelles (www.apdp.bj).

                        <br>En tout état de cause, <B>DKO TECHNOLOGIES</B> ne collecte d’informations 
                            personnelles relatives à l’utilisateur que pour le besoin de certains services 
                            proposés par le site <B>https://dko-technologies.com</B>. L’utilisateur fournit ces 
                            informations en toute connaissance de cause, notamment lorsqu’il procède par luimême à leur saisie. Conformément aux dispositions de la loi 2017-20 portant code 
                            du numérique en République du Bénin, tout utilisateur dispose d’un droit d’accès, 
                            de rectification et d’opposition aux données personnelles le concernant, en 
                            effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité 
                            avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse 
                            doit être envoyée. Aucune de ses informations personnelles n’est publiée à son 
                            insu, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers.

                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>2. Droit d’accès</B>
                        <br>En application de cette loi, les internautes disposent d’un droit d’accès, de 
                            rectification, de modification et de suppression concernant les données qui les 
                            concernent personnellement. Ce droit peut être exercé par voie postale auprès de 
                            DKO TECHNOLOGIES ou par voie électronique à l’adresse email suivante : 
                            contact@dko-technologies.com. Les informations personnelles collectées ne sont 
                            en aucun cas confiées à des tiers. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>3. Confidentialité </B>
                        <br>Vos données personnelles sont confidentielles et ne seront en aucun cas 
                            communiquées à des tiers. A cet effet et conformément à la loi n°2017-20, portant 
                            code numérique en République du Bénin, DKO TECHNOLOGIES s’engage à ne 
                            pas les divulguer. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>4. Propriété intellectuelle </B>
                        <br>Tout le contenu du présent site, incluant, de façon non limitative, les graphismes, 
                            images, textes, vidéos, animations, sons, logos, gifs et icônes ainsi que leur mise en 
                            forme sont la propriété exclusive de DKO TECHNOLOGIES à l’exception des 
                            marques, logos ou contenus appartenant à d’autres sociétés partenaires ou auteurs.
                        <br>Toute reproduction, distribution, modification, adaptation, retransmission ou 
                            publication, même partielle, de ces différents éléments est strictement interdite sans 
                            l’accord express par écrit de DKO TECHNOLOGIES.  
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>5. Conditions de services </B>
                        <br>Les services de DKO TECHNOLOGIES sont édités par DKO SARL, entreprise 
                            béninoise immatriculée auprès du Registre du Commerce et du Crédit Mobilier 
                            sous le numéro RB/COT/18 B 21738 dont le siège social est situé à Houéyiho, Ilot 
                            1409 B-Maison SEKLOKA Norbert, dans la ville de Cotonou, en République 
                            Bénin.
                    </p>
                </div>
            </article>
        </div>
    </div>
</div>

<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>
