<div class="login-card">
  <?php if(isset($error)):?>
    <div class="message">
      <span><?=$error;?></span>
    </div>
  <?php endif;?>
  <div class="login-content">
    <h1>Modification du mot de passe</h1>
    <?php if(isset($message3)):?>
          <span class="notification"><?php echo $message3 ?></span>
        <?php endif;?>
    <form class="d-flex flex-column align-items-center" action="" method="post">
      <div class="login-input">
        <!--<span>Mot de passe</span>-->
        <input type="password" name="password1" placeholder="Entrer le nouveau mot de passe">
        <?php if(isset($message1)):?>
          <span class="notification"><?php echo $message1 ?></span>
        <?php endif;?>
      </div>
      <div class="login-input">
        <!--<span>Mot de passe</span>-->
        <input type="password" name="password2" placeholder="Confirmer le nouveau mot de passe">
        <?php if(isset($message2)):?>
          <span class="notification"><?php echo $message2 ?></span>
        <?php endif;?>
      </div>
      <div class="btn-submit">
        <!--<a class="btn-login" href="/pages/index.html">Connecter</a>-->
        <button class="btn-login" name="valider">Valider</button>
        
      </div>       
    </form>
  </div>
</div>