<?php
$carouselActive = false;

include _VIEW_PATH . "/common_header.phtml"; ?>

<!-- Header -->
<?php include _VIEW_PATH."common_top_bar.phtml"; ?>
<!-- End Header -->
<section class="page-banners">
     <!--<div> <img class="img-banners" src="<?php echo $iniObj->UIPath; ?>/images/hero/banner-nos-services.jpg" alt="" srcset=""></div>-->
     <div class="container">
         <div class="banner-content text-center">
            <h2>Politique de confidentialité</h2>
                <div class="page-breadcrumbs">
                    <nav aria-label="breadcrumbs">
                        <ol class="breadcrumbs breadcrumb">
                            <li class="breadcrumb-item"><a href="<?php $lib->customerSite ?>">Acceuil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Politique de confidentialité</li>
                        </ol>
                    </nav>
                </div>
         </div>
     </div>
</section>
<div class="container g-py-40">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <!-- Blog Minimal Blocks -->
            <article class="g-mb-">
                <div class="g-mb-30">
                    <h2 id="article" class="h4 g-color-black g-font-weight-600 mb-3"><a class="u-link-v5 g-color-black g-color-primary--hover" href="" style="font-size :25px;">Politique de confidentialité</a></h2>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>DKO TECHNOLOGIES</B>, conscient de l’importance du respect de la vie privée et 
                        de confidentialité des données à caractère personnel qu’il traite, s’engage à protéger 
                        les données à caractère personnel que vous lui confiez. Vous trouverez ci-après les 
                        mesures que nous prenons à l’égard de cette catégorie de données. Notre politique 
                        de confidentialité pourra faire l’objet de modification en fonction des évolutions 
                        légales et des recommandations conformément à la loi du numérique en République 
                        du Bénin. Aucune donnée transmise par l’intermédiaire de notre site ne pourra être 
                        consultée par un tiers non autorisé. <B>DKO TECHNOLOGIES</B> prend toutes les 
                        précautions utiles pour préserver la sécurité de ces données et notamment, 
                        empêcher qu’elles soient déformées, altérées ou endommagées. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>I.DEFINITIONS</B>
                        <br>Donnée à caractère personnel : toute information relative à une personne physique 
                            ou morale identifiée ou qui peut être identifiée, directement ou indirectement, par référence à un numéro d’identification ou à un ou plusieurs éléments qui lui sont 
                            propres. 

                        <br>Utilisateur : toute personne physique majeure capable (particulier ou 
                            professionnel), ou toute personne morale, utilisant les services qui sont proposés 
                            sur le site <B>https://dko-technologies.com.</B>

                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>II. Collecte et diffusion des données à caractère personnel </B>
                        <br><B>DKO TECHNOLOGIES</B> est susceptible de collecter des données à caractère 
                            personnel liées à l’utilisateur notamment lors : 
                        <br>&ensp;&ensp;&ensp;• De la navigation sur le site ; 
                        <br>&ensp;&ensp;&ensp;• D’une demande de renseignement ou de prise de contact ; 
                        <br>&ensp;&ensp;&ensp;• De la rédaction d’un commentaire ; 


                        <br>Nous recueillerons, transférerons, traiterons et entreposons vos données 
                            personnelles qu’avec votre permission expresse, sauf si cela est légalement requis, 
                            et nous n’utilisons ces informations qu’à des fins légales ou contractuelles pour 
                            lesquelles elles sont requises. Les informations susceptibles d’être collectées par 
                            <B>DKO TECHNOLOGIES</B> sont celles ayant trait à l’identité de l’utilisateur, à ses 
                            coordonnées postales et/ou électroniques. De manière non limitative il pourra s’agir 
                            de votre nom, adresse mail, numéro de téléphone, adresse résidentielle, numéro 
                            d’identification, l’identification du périphérique et l’emplacement de l’appareil 
                            ainsi que d’autres informations personnelles à partir de notre base de système et 
                            dans le cadre de votre demande de devis sur la plateforme <B>DKO 
                            TECHNOLOGIES</B>, des cookies, l’adresse IP, les périphériques mobiles et 
                            identificateurs publicitaires, la version du navigateur, le type et la version du 
                            système d’exploitation, les informations sur le réseau mobile, les paramètres du 
                            périphérique et données logicielles. Toutes les données à caractère personnel 
                            recueillies par <B>DKO TECHNOLOGIES</B> sont obligatoires et/ou nécessaires pour bénéficier des services proposés par <B>DKO TECHNOLOGIES</B>. Chaque donnée 
                            collectée est en accord avec la ou les finalité(s) poursuivie(s). 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>III. Légitimité de la conservation des données à caractère personnel </B>
                        <br>Les données à caractère personnel de l’utilisateur sont conservées jusqu’à leur 
                                suppression à la demande de l’utilisateur ou par la société. 
                        <br>DKO TECHNOLOGIES conservera dans ses systèmes informatiques et dans des 
                            conditions raisonnables de sécurité une preuve des transactions conformément aux 
                            dispositions de tout Acte Uniforme de l’Organisation pour l’harmonisation en 
                            Afrique du droit des affaires (OHADA) notamment celui relatif au droit 
                            commercial général, de la loi portant réglementation des Système financiers 
                            décentralisés adoptée le 6 avril 2007 par le Conseil des Ministres de l’UMOA, 
                            l’Instruction n°03002-2009 fixant les modalités d’établissement et de conservation 
                            des états financiers des systèmes financiers décentralisés de l’Union Monétaire 
                            Ouest Africaine relatives à la durée de conservation des livres et documents créés à 
                            l’occasion d’activités commerciales et de l’Instruction n°008-05 2015 régissant les 
                            conditions et modalités d’exercice des activités des émetteurs de monnaie 
                            électronique dans les états membres de l’union Monétaire Ouest Africaine 
                            (UMOA) et la loi n°2017-20 du 20 avril 2018 portant code du numérique en 
                            République du Bénin relatives à la conservation des contrats conclus par voie 
                            électronique ainsi que tout autre texte en vigueur au moment de la publication de la 
                            présente Politique. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>IV. Sécurité et conservation des données à caractère personnel </B>
                        <br>Nous nous efforçons de maintenir un niveau de sécurité adapté au risque associé au 
                            traitement des données à caractère personnel. Au sein de DKO TECHNOLOGIES, 
                            nous prenons des mesures organisationnelles, techniques et administratives afin 
                            d’empêcher l’accès illicite à vos données à caractère personnel, ainsi que leur 
                            destruction, perte, altération ou détournement. Seuls les employés ayant besoin 
                            d’accéder à vos données à caractère personnel pour mener à bien leurs tâches 
                            professionnelles y ont accès. Malheureusement, il est impossible de garantir qu’un 
                            quelconque système de stockage ou de transmission des données soit sûr à 100 %. Si vous avez des raisons de croire que les interactions que vous avez avec nous ne 
                            sont plus sécurisées (par exemple, si vous pensez que la sécurité de votre compte 
                            est compromise), veuillez nous contacter immédiatement. 
                        <br>Si vous êtes client de DKO TECHNOLOGIES, nous conservons vos données à 
                            caractère personnel pendant toute la durée du contrat de prestation qui nous lie à 
                            vous. Nous conservons vos données à caractère personnel après avoir cessé de vous 
                            fournir des services. 
                        <br>Nous conservons également vos données à caractère personnel afin de nous 
                            conformer à nos obligations fiscales, comptables et financières, lorsque nos 
                            engagements contractuels nous y obligent. Lorsque nous conservons des données, 
                            nous le faisons conformément aux délais de prescription en vigueur et aux 
                            obligations de conservation prescrites par le droit applicable. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>V. Utilisation de vos données </B>
                        <br>Nous utilisons les données nécessaires dans le cadre de l’assistance clientèle pour 
                            enquêter, répondre et résoudre les problèmes de réclamations et de services. 
                        <br>Si la loi l’exige ou que nous pensons que cela est nécessaire, nous utilisons vos 
                            données (y compris vos communications) pour des raisons de sécurité ou afin 
                            d’enquêter sur d’éventuelles violations de nos conditions générales d’utilisation ou 
                            de cette politique de confidentialité.
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>VI. Consentement à la Communication et au traitement </B>
                        <br>Nous vous contacterons par e-mail, services de message court (SMS), appel 
                            téléphonique ou autres manières par le biais de nos services, y compris des 
                            messages texte et des notifications push. Nous vous enverrons des messages sur la 
                            disponibilité de nos services, la sécurité, ou d’autres problèmes liés au service. 
                            Nous envoyons également des messages sur la façon d’utiliser les services et les 
                            mises à jour de réseau.
                        <br>Lorsque vous utilisez ou interagissez avec nos services, vous consentez au 
                            traitement des données, partage, transfert et l’utilisation de vos informations tel 
                            qu’indiqué dans cette politique de confidentialité. <B>DKO TECHNOLOGIES </B>
                            s’efforcera de respecter toutes les réglementations applicables en matière de 
                            protection des données et de confidentialité. 
                        <br>Dans le cadre de tous les arrangements de partage, <B>DKO TECHNOLOGIES</B> exige 
                            que ses fournisseurs de services et ses partenaires actuels et futurs maintiennent ces 
                            renseignements dans des règles strictes en matière de protection des données 
                            personnelles et leur interdit de divulguer ces renseignements à quiconque pour 
                            d’autres fins. 
                        <br>Nous ne partageons pas, et ne partagerons pas, les informations des clients avec des 
                            sociétés dans le but de leur permettre de commercialiser leurs produits et services à 
                            nos clients. Nous ne divulguons aucun renseignement personnel non public sur nos 
                            clients à d’autres tiers, sauf si la loi le permet ou l’exige. 
                        <br>En utilisant nos services, vous consentez à ce que nous transférons vos 
                            informations à des pays extérieurs à votre juridiction locale, si nécessaire, aux fins 
                            de sécurité, aux fins commerciales légitimes de <B>DKO TECHNOLOGIES</B>, telles que 
                            définies dans notre politique de confidentialité. Nous nous engageons à garantir la 
                            protection de vos informations et à mettre en œuvre des garanties de sécurité 
                            conformément à la loi applicable. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>VII. Hébergement et sécurisation des données à caractère personnel </B>
                        <br>Le site <B>https://dko-technologies.com</B> est hébergé par <B>https://aws.amazon.com </B>.
                        <br>La protection de nos systèmes et de l’information de nos utilisateurs est primordiale 
                            pour garantir la qualité chez DKO TECHNOLOGIES, sur ses sites Web, les 
                            applications, les services de publicité, les prestations.
                        <br><B>DKO TECHNOLOGIES</B> a mis des garanties techniques, administratives et 
                            physiques en place pour aider à se protéger des accès non autorisés, contre 
                            l’utilisation ou la divulgation des informations que nous recueillons et stockons.
                        <br>Nous mettons en œuvre une variété de mesures de sécurité pour maintenir en sûreté 
                            vos données personnelles lorsque vous les saisissez, soumettez ou accédez à vos 
                            données personnelles. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>VIII. Droit d’accès et de suppression des données à caractère personnel par 
l’utilisateur </B>
                        <br>Tout utilisateur du site dispose d’un droit d’accès, de rectification, d’opposition, et 
                            d’effacement de vos données à caractère personnel mais également d’un droit à la 
                            limitation et à la portabilité de vos données. Il a également la possibilité de déposer 
                            une plainte auprès des autorités de supervision compétentes. Si, il lui a été demandé 
                            de consentir à la collecte, au traitement et au transfert de vos données personnelles, 
                            il a le droit de retirer ce consentement à tout moment. Il peut exercer ce droit via 
                            l’adresse suivante : contact@dko-technologies.com 
                        <br>Les articles de ce site peuvent inclure des contenus intégrés (par exemple des 
                            vidéos, images, articles…). Le contenu intégré depuis d’autres sites se comporte de 
                            la même manière que si le visiteur se rendait sur cet autre site. 
                        <br>Ces sites web pourraient collecter des données sur vous, utiliser des cookies, 
                            embarquer des outils de suivis tiers, suivre vos interactions avec ces contenus 
                            embarqués si vous disposez d’un compte connecté sur leur site web. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>IX. Utilisation de cookies </B>
                        <br><B>DKO TECHNOLOGIES</B> informe l’utilisateur qu’elle peut être amenée à utiliser 
                            des cookies. Ce dernier accepte expressément ou implicitement l’utilisation des 
                            cookies en poursuivant sa navigation sur le site.
                        <br>Un cookie est un fichier texte susceptible d’être enregistré dans un terminal lors de 
                            la consultation d’un service en ligne avec un logiciel de navigation. Un fichier 
                            cookie permet à son émetteur, pendant sa durée de validité, de reconnaître le 
                            terminal concerné à chaque fois que ce terminal accède à un contenu numérique 
                            comportant des cookies du même émetteur. 
                        <br>Les cookies émis par DKO TECHNOLOGIES permettent : 
                        <br>• D’établir des statistiques et volumes de fréquentation et d’utilisation des divers 
                            éléments composant notre Site, nous permettant d’améliorer la configuration, 
                            l’intérêt, le design et l’ergonomie de nos services ; 
                        <br>• D’adapter la présentation de notre site aux préférences d’affichage de votre 
                            terminal (langue utilisée, résolution d’affichage, système d’exploitation utilisé, etc.) 
                            lors de vos visites sur notre site, selon les matériels et les logiciels de visualisation 
                            ou de lecture que votre terminal comporte ; 
                        <br>• De mémoriser des informations relatives à des produits, services ou informations 
                            que vous avez choisis sur notre Site (contenu d’un panier de commandes, etc.) 
                        <br>Vous pouvez à tout moment configurer votre logiciel de navigation de manière à ce 
                            que des cookies soient enregistrés dans votre terminal ou, au contraire, qu’ils soient 
                            rejetés (soit systématiquement, soit selon leur émetteur). Vous pouvez également 
                            configurer votre logiciel de navigation de manière à ce que l’acceptation ou le refus 
                            des cookies vous soient proposés ponctuellement, avant qu’un cookie puisse être 
                            enregistré dans votre terminal. 
                        <br>Attention : tout paramétrage est susceptible de modifier votre navigation sur 
                            Internet et vos conditions d’accès à certains services nécessitant l’utilisation de 
                            cookies.
                        <br>Pour la gestion des cookies et de vos choix, la configuration de chaque navigateur 
                            (Internet Explorer, Firefox, Safari, Edge, Google Chrome) est différente. Elle est 
                            décrite dans le menu d’aide de votre navigateur, qui vous permettra de savoir de 
                            quelle manière modifier vos souhaits en matière de cookies. 
                    </p>
                    <p class="g-color-black g-line-height-1_8" style="text-align : justify;"><B>X. Mises à jour de la Politique de confidentialité</B>
                        <br>Les parties conviennent que DKO TECHNOLOGIES dispose du droit d’apporter 
                            des modifications à la présente politique de confidentialité de temps à autre 
                            notamment pour des raisons techniques, financières, de conformité, de sécurité afin 
                            d’y incorporer de nouveaux services ou des mises à jour, les changements affectant 
                            nos pratiques concernant le traitement des données à caractère personnel ou les lois 
                            applicables. Tous les changements prennent effet au moment où nous publions sur 
                            le site de DKO TECHNOLOGIES la politique de confidentialité révisée sur les 
                            services. Ladite notification vaut information et élude la responsabilité de DKO 
                            TECHNOLOGIES quant à tout préjudice qui découlerait de l’ignorance de 
                            l’utilisateur. Pour toutes questions concernant cette politique de confidentialité ou 
                            un incident de violation de données que vous souhaitez signaler, veuillez nous 
                            contacter par mail à <B>contact@dko-technologies.com</B>
                    </p>
                </div>
            </article>
        </div>
    </div>
</div>

<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>
