<?php if($iniObj->debugViews) echo __FILE__ ; ?>
<!--=== Product Content ===-->



<div class="container">
  <?php
    include _VIEW_PATH.$lib->lang."/search_bar.phtml";
  ?>
	<!-- Products -->
	<?php if ($nbResult->total>0) {?>
	<div class="row g-pt-30 g-mb-20">
	
		<div class="col-lg-4 text-center">
			<h2 class="badge-results">
				<?php
				echo $nbResult->total ;
					if($nbResult->total >1) echo " articles"; else echo " article"; ?>
			</h3>
		</div>

		<div class="col-lg-8 text-center">
			<h1 class="title-uppercase">Vos résultats</h2>
		</div>
	</div>

	<!--=== List resultats p ===-->
	<div class="row  g-pt-10 g-mb-20 ">
	<?php foreach($product['data'] as $k=>$v) {
        if(file_exists(realpath(_WEB_FILES."/filesLib/articles_img/" . $v->libelle . "/" . $v->photo2))){
        ?>

        <div class="col-6 col-lg-3 g-mb-30">
          <?php include _VIEW_PATH.$lib->lang."/product_card_component.phtml"; ?>
        </div>
		<?php }
	} ?>

	</div>
	<?php }

	else{ ?>
	
		<div class="container text-center g-py-100">
        <div class="mb-5">
          <span class="d-block g-color-gray-light-v1 g-font-size-70 g-font-size-90--md mb-4">
            <i class="icon-science-032 u-line-icon-pro"></i>
          </span>
          <h2 class="g-mb-30">Aucun résultat trouvé pour votre recherche</h2>
        </div>
        <a class="btn u-btn-primary g-font-size-12 text-uppercase g-py-12 g-px-25" href="/">Retourner à l'accueil</a>
      </div>

      

	<?php } ?>


  <!--=== pagination===-->
	<div class="text-center">
		<ul class="pagination pagination-v2">
			<?php
			$pagination->paginate($pages_requested,$currentPage);
			?>
		</ul>
	</div>
	<!--/end pagination-->

</div>
<!--=== End Product Content ===-->


