<?php if ($iniObj->debugViews) echo __FILE__; ?>

<!-- Product -->
<?php //$lib->debug($v); ?>

<div class="card bg-light mb-3">
  <div class="">
    <figure class="g-pos-rel ">
      <a href="/article_<?php echo $v->productId . "_" . $lib->cleanUrl($v->libelle); ?>">
        <img class="img-fluid" src="<?php echo $iniObj->imgPath . $v->photo1; ?>" alt="Image Description">
      </a>
      <?php if ($v->currentPrice < $v->initalPrice) { ?>
        <figcaption class="w-100 g-bg-primary g-bg-black--hover text-center g-pos-abs g-bottom-0 g-transition-0_2 g-py-5">
          <a class="g-color-white g-font-size-11 text-uppercase g-letter-spacing-1 g-text-underline--none--hover" href="#">PROMO</a>
        </figcaption>
      <?php } ?>
    </figure>
  </div>
  <div class="card-body">

    <div class="media">
      <!-- Product Info -->
      <div class="d-flex flex-column">
        <h4 class="h6 g-color-black mb-1" style="min-height: 40px;">
          <a class="product-review" href="/article_<?php echo $v->productId . "_" . $lib->cleanUrl($v->libelle); ?>">
            <div class="tooltip_wrapper"><?php echo substr($v->libelle, 0, 40) . '...'; ?>
              <span class="tooltiptext"><?php echo $v->libelle ?></span>
            </div>
          </a>
        </h4>
        <a class="d-inline-block g-color-gray-dark-v5 g-font-size-13" href="/rayon_<?php echo $v->subCategoryCode . "_" . $lib->cleanUrl($v->subCategoryDescription); ?>"><?php echo $v->subCategoryDescription; ?>
        </a>
        <a class="d-inline-block g-color-gray-dark-v5 g-font-size-13" href="/magasin_<?php echo $v->storeUrl; ?>"><?php echo $v->storeName; ?> </a>
        <span class="d-inline-block g-color-black g-font-size-17">
          <span class="title-price line-through"><?php echo $v->currentPrice; ?> &euro;</span>
          <?php if ($v->currentPrice < $v->initalPrice) { ?>
            <span class="title-price line-through text-danger"><del><?php echo $v->initalPrice; ?> &euro;</del></span>
          <?php } ?>
        </span>
      </div>
      <!-- End Product Info -->

      <!-- Products Icons -->
      <ul class="list-inline media-body text-right">
        <?php if (/*$iniObj->cartActive*/1 == 1) { ?>
          <li class="list-inline-item align-middle mx-0">
            <a class="add-to-cart u-icon-v1 u-icon-size--sm g-color-gray-dark-v5 g-color-primary--hover g-font-size-15 rounded-circle add-to-cart" href="#" data-toggle="tooltip" data-placement="top" data-productid="<?php echo $v->productId; ?>" data-productname="<?php echo $v->libelle; ?>" data-productimage="<?php echo $iniObj->imgPath . $v->photo1; ?>" data-productprice="<?php echo $v->currentPrice; ?>" data-productstorecode="<?php echo $v->storeCode; ?>" data-productstorename="<?php echo $v->storeName; ?>" data-productemailmagasin="<?php echo $v->email_magasin; ?>" data-productemaildirecteur="<?php echo $v->email_directeur; ?>" data-qtestock="<?= $v->qte_stock ?>" title="Ajouter au panier">
              <i class="icon-finance-100 u-line-icon-pro"></i>
            </a>
          </li>
        <?php } ?>
      </ul>
      <!-- End Products Icons -->

    </div>

  </div>
</div>



<!-- End Product -->