<?php
	if($iniObj->debugViews) echo __FILE__ ;
	$carouselActive = true;
	$title = "Articles neufs et occasions - Professionnel - Dépôt vente - Electroménager - Décoration - Informatique - Jeux vidéo - Son - Image - Téléphonie - Bricolage - Jardinage - Animalerie";

	include _VIEW_PATH."/common_header.phtml";?>

	<?php
		// include _VIEW_PATH."common_top_bar.phtml";
		if($storeActive==1){
			include _VIEW_PATH.$lib->lang."/top_menu_magasin.phtml";
		}
		else{
			include _VIEW_PATH.$lib->lang."/top_menu.phtml";
		}
	?>

	<?php
		include _VIEW_PATH.$lib->lang."/product_search_page_content.phtml";
	?>

	<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
	<?php include _VIEW_PATH."/common_include_files.phtml";?>