  <!-- START Page Banner -->
  <section class="page-banner">
      <div class="container">
          <div class="banner-content text-center">
              <h2>Project Details</h2>
              <div class="page-breadcrumb">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                          <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                          <li class="breadcrumb-item active" aria-current="page">Pages</li>
                      </ol>
                  </nav>
              </div>
          </div>
      </div>
  </section>
  <!-- END Page Banner -->

  <!-- START Project Details Content -->
  <section class="project-details-content pt-120 rpt-100 pb-70">
      <div class="container">
          <div class="project-details-content-inner">
              <div class="project-details-image">
                  <img src="<?php echo $iniObj->UIPath; ?>/images/project/project-details.jpg" alt="Project Details Image" />
              </div>
              <div class="project-info-box">
                  <div class="row align-items-center">
                      <div class="col-lg-4 col-12">
                          <div class="project-info-text">
                              <h4>Project<br /> Information</h4>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6">
                          <div class="client-content">
                              <ul>
                                  <li><span>Clients </span> Marian Crant</li>
                                  <li><span>Category </span> Data Management</li>
                                  <li><span>Date </span> 22 August 2021</li>
                              </ul>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6">
                          <div class="client-content">
                              <ul>
                                  <li><span>Website </span> <a href="https://www.domain.com/">www.domain.com</a></li>
                                  <li><span>Location </span> America</li>
                                  <li><span>Duration </span> 04 months.</li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
              <h2>The Best IT Practices in Cloud And Security.</h2>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book. It has survived no only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.</p>
              <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the reease and more recent. Lorem Ipsum is simply dummy text of the pinting and typesetting industry. typesetting, remaining on essentially unchanged. It was popular of the reease and more recent.</blockquote>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book. It has survived no only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.</p>
              <div class="project-result-area">
                  <div class="row">
                      <div class="col-lg-7">
                          <div class="project-result-video">
                              <a class="video-play mfp-iframe" href="https://www.youtube.com/watch?v=aFWhf2wjJYo&amp;list=PLUoqTnNH-2XxOt7UsKlTqbfrA2ucGosCR">
                                  <i class="icofont-ui-play"></i>
                              </a>
                          </div>
                      </div>
                      <div class="col-lg-5">
                          <div class="project-result-image">
                              <img src="<?php echo $iniObj->UIPath; ?>/images/project/project-result2.jpg" alt="Project Result Image" />
                          </div>
                      </div>
                  </div>
              </div>
              <h2>Project Result & Benefits of Project</h2>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book. It has survived no only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.</p>
              <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the reease and more recent. Lorem Ipsum is simply dummy text of the pinting and typesetting industry. typesetting, remaining on essentially unchanged. It was popular of the reease and more recent.</blockquote>
              <div class="related-project">
                  <h2>Related Project</h2>
                  <div class="row">
                      <div class="col-lg-4 col-md-6">
                          <div class="project-item">
                              <div class="project-image">
                                  <img src="<?php echo $iniObj->UIPath; ?>/images/project/project1.jpg" alt="Project Image" />
                              </div>
                              <div class="project-content">
                                  <a href="projectdetails.html" class="project-icon">
                                      <i class="icofont-arrow-right"></i>
                                  </a>
                                  <h5><a href="projectdetails.html">IT Management Services.</a></h5>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6">
                          <div class="project-item">
                              <div class="project-image">
                                  <img src="<?php echo $iniObj->UIPath; ?>/images/project/project2.jpg" alt="Project Image" />
                              </div>
                              <div class="project-content">
                                  <a href="projectdetails.html" class="project-icon">
                                      <i class="icofont-arrow-right"></i>
                                  </a>
                                  <h5><a href="projectdetails.html">Branding Development.</a></h5>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4 col-md-6">
                          <div class="project-item">
                              <div class="project-image">
                                  <img src="<?php echo $iniObj->UIPath; ?>/images/project/project4.jpg" alt="Project Image" />
                              </div>
                              <div class="project-content">
                                  <a href="projectdetails.html" class="project-icon">
                                      <i class="icofont-arrow-right"></i>
                                  </a>
                                  <h5><a href="projectdetails.html">UI/UX Design Strategy.</a></h5>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- END Project Details Content -->

  <!-- START Call To Action -->
  <section class="cta-section pb-120 rpb-100 bg-white">
      <div class="container">
          <div class="contact-withus">
              <div class="row">
                  <div class="col-lg-7">
                      <div class="contact-withus-content">
                          <h3>Contact With Us.<br /> To Require a Detailed Analysis of Your Plan.</h3>
                      </div>
                  </div>
                  <div class="col-lg-5">
                      <div class="contact-withus-num">
                          <a class="contact-number" href="callto:0095788394">+00 95 788 394</a>
                          <a href="contact.html" class="btn theme-btn">Contact Today<i class="icofont-double-right"></i></a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- END Call To Action -->