<div class="img-connexion">
    <div class="login-card">
    <!--<img class="login-header" src="/img/logo.png" alt="">-->
    <div class="center">
      <a href="<?php $lib->customerSite ?>/">
        <img src="<?php $lib->customerSite ?>/UIResources/logo2.png" alt="Logo GEMO" style="width:187px" srcset="">
      </a>
    </div>
    <?php if(isset($error)):?>
      <div class="message">
        <span><?=$error;?></span>
      </div>
    <?php endif;?>
    <div class="login-content">
      <h1>Reinitialisation de mot de passe</h1>
      <form action="" method="post">
        <input type="hidden" name="token" value="<?=$_SESSION['token'];?>">
        <div class="login-input">
          <!--<span>Mot de passe</span>-->
          <input type="password" name="password1" placeholder="Entrer l'ancien mot de passe">
          <?php if(isset($message1)):?>
            <span class="notification"><?php echo $message1 ?></span>
          <?php endif;?>
        </div>

        <div class="login-input">
          <!--<span>Mot de passe</span>-->
          <input type="password" name="password2" placeholder="Entrer le nouveau mot de passe">
          <?php if(isset($message2)):?>
            <span class="notification"><?php echo $message2 ?></span>
          <?php endif;?>
        </div>

        <div class="login-input">
          <!--<span>Mot de passe</span>-->
          <input type="password" name="password3" placeholder="Confirmer le nouveau mot de passe">
          <?php if(isset($message3)):?>
            <span class="notification"><?php echo $message3 ?></span>
          <?php endif;?>
        </div>

        <div class="btn-submit">
          <!--<a class="btn-login" href="/pages/index.html">Connecter</a>-->
          <button class="btn-login" name="reinitialiser">Reinitialiser</button>

        </div>       
      </form>
    </div>
  </div>
</div>
