<main>
            <h2 class="main-title">Licences secondaires</h2>
            <div class="track padding-bottom-20">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $param2[0];?></span><span>/</span><span><?php echo $url_array[3];?></span>
            </div>

            <?php if($show) : ?>
            
            <?php else : ?>
                <div class="main-btn">
                    <a href="<?php echo $url_array[4];?>/addLicenceSecondaire" id="myBtn"><i class="fas fa-plus" style="margin-right:15px ;"></i>Ajouter une nouvelle licence secondaire</a>
                </div>
            <?php endif ;?>
            <section class="recent">
                <div class="activity">
                    <div style="padding-top: 5px;" class="activity-card">
                        <h3>Liste des licences secondaires</h3>
                        <div class="table-responsive">
                            <div class="research">
                                <div>
                                    <div id="form-research"><input id="filter" type="text" placeholder="Rechercher..."></div>
                                    <i class="fas fa-search"></i>
                                </div>
                            </div>
                            <table id="table" class="table table-striped" style="margin-top: 30px;" border="0">
                                <thead>
                                    <tr>
                                        <th>Licence key</th>
                                        <th>Date d'activation</th>
                                        <th>Date d'expiration</th>
                                        <th>Statut</th>
                                        <th style="text-align:center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   <?php if(isset($data['licences'])): ?>
                                        <?php foreach($data['licences'] as $licence): ?>
                                        <tr>
                                             <td><?=$licence['licence_key'] ?></td>
                                             
                                             <td><?=$licence['activation_date'] ?></td>
                                             <td><?=$licence['expiration_date'] ?></td>
                                             <td>
                                                  <?php if($licence['is_active'] == 1): ?>
                                                       <span class="span-success success">Activer</span>
                                                  <?php endif; ?>
                                                  <?php if($licence['is_active'] == 0): ?>
                                                       <span class="span-success danger">Bloquer</span>
                                                  <?php endif; ?>
                                                  <!--<?php //if($licence['is_active'] == 2): ?>
                                                       <span class="span-success danger">Revoquer</span>
                                                  <?php //endif; ?>-->
                                             </td>
                                             
                                             <td style="display:flex">
                                                  <!--<span onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/activer/<?=$licence['licence_id'] ?>'" class="btn-action white pg-5 success cursor"> Activer</span>-->
                                                  <span onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/bloquer/<?=$licence['licence_id'] ?>'" class="btn-action white pg-5 danger cursor">Bloquer</span>
                                                  <span onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/modifier/<?=$licence['licence_id'] ?>'" class="btn-action white pg-5 primary cursor">Réactiver</span>
                                             </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    
                                </tbody>
                            </table>
                        </div>   
                    </div>
                </div>
            </section>
        </main>