<!-- Main Content-->
<div class="main-content side-content pt-0">

    <div class="container-fluid">
        <div class="inner-body">

            <?php if(!empty($_SESSION['notification'])):?>
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
            <?=$_SESSION['notification']?>
            <?php endif; ?>

                <!-- Page Header -->
                <div class="page-header">

                    <div>
						<h2 class="main-content-title tx-24 mg-b-5">Licences Secondaires</h2>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><?= $url_array[1] ?></a></li>
							<li class="breadcrumb-item active" aria-current="page"><?= $url_array[2] ?></li>
						</ol>
					</div>
							
					

                </div>
                <!-- End Page Header -->

                <!-- Row -->
                <div class="row row-sm">
                    <div class="col-lg-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div>
                                    <h6 class="main-content-label mb-1">Liste des sous-licences</h6>
                                    <p class="text-muted card-sub-title"></p>
                                </div>
                                <div class="table-responsive">
                                    <table id="example3" class="table table-striped table-bordered text-nowrap" >
                                    <thead>
                                    <tr>
                                        <th>Licence key</th>
                                        <th>Date d'activation</th>
                                        <th>Date d'expiration</th>
                                        <th>Statut</th>
                                        <th style="text-align:center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   <?php if(isset($data['licences'])): ?>
                                        <?php foreach($data['licences'] as $licence): ?>
                                        <tr>
                                             <td><?=$licence['licence_key'] ?></td>
                                             
                                             <td><?=$licence['activation_date'] ?></td>
                                             <td><?=$licence['expiration_date'] ?></td>
                                             <td>
                                                  <?php if($licence['is_active'] == 1): ?>
                                                       <span class="badge badge-pill badge-primary-light">Activer</span>
                                                  <?php endif; ?>
                                                  <?php if($licence['is_active'] == 0): ?>
                                                       <span class="badge badge-pill badge-warning-light">Bloquer</span>
                                                  <?php endif; ?>
                                                  <!--<?php //if($licence['is_active'] == 2): ?>
                                                       <span class="span-success danger">Revoquer</span>
                                                  <?php //endif; ?>-->
                                             </td>
                                             
                                             <td style="display:flex">
                                                    <?php if($licence['is_active'] == 1): ?>
                                                        <span onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/bloquer/<?=$licence['licence_id'] ?>'" class="btn ripple btn-primary">Bloquer</span>
                                                  <?php endif; ?>
                                                  <?php if($licence['is_active'] == 0): ?>
                                                    <span onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/modifier/<?=$licence['licence_id'] ?>'" class="btn ripple btn-info">Réactiver</span>
                                                  <?php endif; ?>
                                                  <!--<span onclick="document.location='<?php $lib->customerSite ?>/licences/secondaire/activer/<?=$licence['licence_id'] ?>'" class="btn-action white pg-5 success cursor"> Activer</span>-->
                                                  
                                             </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    
                                </tbody>
                                    
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->    
        </div>
    </div>
</div>
<!-- End Main Content-->
