<!-- Main Content-->
<div class="main-content side-content pt-0">

    <div class="container-fluid">
        <div class="inner-body">

            <?php if(!empty($_SESSION['notification'])):?>
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
            <?=$_SESSION['notification']?>
            <?php endif; ?>

                <!-- Page Header -->
                <div class="page-header">


                    <?php include _VIEW_PATH."common_top_for_dashboard_content.phtml"; ?>

                </div>
                <!-- End Page Header -->

                <!-- Row -->
                <div class="row row-sm">
                    <div class="col-lg-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div>
                                    <h6 class="main-content-label mb-1">Utilisateurs</h6>
                                    <!-- <p class="text-muted card-sub-title">Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.</p> -->
                                </div>
                                <div class="table-responsive">
                                    <table id="example3" class="table table-striped table-bordered text-nowrap" >
                                    <thead>
                                            <tr>
                                                <th class="text-center">Nom et prenom du manager</th>
                                                <th class="text-center">Téléphone</th>
                                                <th class="text-center">Statut</th>
                                                <th style="text-align:center">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if(!empty($data['manager'])):?>
                                                <?php foreach($data['manager'] as $manager):?>
                                                    <tr class="text-center">
                                                        <td><?=$manager['firstname']?> <?=$manager['lastname']?></td>
                                                        <td><?=$manager['phone_number']?></td>
                                                        <td>
                                                        <?php if($manager['is_active_flag'] == 1): ?>
                                                            <span class="badge badge-pill badge-primary-light">Activer</span>
                                                        <?php endif; ?>
                                                        <?php if($manager['is_active_flag'] == 0): ?>
                                                            <span class="badge badge-pill badge-warning-light">Bloquer</span>
                                                        <?php endif; ?>
                                                        </td>
                                                        <td style="display:flex">
                                                            <span onclick="document.location='<?php $lib->customerSite ?>/administration/utilisateurs/password/<?=$manager['user_id']?>'" class="btn ripple btn-primary">Modifier le mot de passe</span>
                                                            <span onclick="document.location='<?php $lib->customerSite ?>/administration/utilisateurs/informations/<?=$manager['user_id']?>'" class="btn ripple btn-info">Modifier les informations</span>

                                                        </td>
                                                    </tr>
                                                <?php endforeach;?>
                                            <?php endif;?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->    
        </div>
    </div>
</div>
<!-- End Main Content-->