<!-- Main Content-->
<div class="main-content side-content pt-0">

    <div class="container-fluid">
        <div class="inner-body">
                <!-- Page Header -->
                <div class="page-header">

					<div>
						<h2 class="main-content-title tx-24 mg-b-5">Utilisateurs</h2>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><?= $url_array[1] ?></a></li>
							<li class="breadcrumb-item active" aria-current="page"><?= $url_array[2] ?></li>
						</ol>
					</div>
							
					<div class="d-flex">
						<div class="justify-content-center">
							<button onclick="document.location='<?php $lib->customerSite ?>/utilisateurs/ajouter'" type="button" class="btn btn-primary my-2 btn-icon-text">
								<i class="fas fa-plus mr-2"></i> Ajouter un nouveau utilisateurs
							</button>
						</div>
					</div>

                </div>
                <!-- End Page Header -->

                <!-- Row -->
                <div class="row row-sm">
                    <div class="col-lg-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div>
									<h6 class="main-content-label mb-1">Liste des utilisateurs</h6>
								</div>
                                <div class="table-responsive">
                                    <table id="example2" class="table table-striped table-bordered text-nowrap" >
                                    <thead>
										<tr>
                                            <th>Nom & Prenoms</th>
                                            <th>Téléphone</th>
                                            <th>Email</th>
                                            <th>Profils</th>
                                            <th>Statut</th>
                                            <th>Actions</th>
										</tr>
									</thead>
												<tbody>
                                                <?php if(!empty($data['utilisateurs'])):?>
                                                    <?php foreach($data['utilisateurs'] as $utilisateur):?>
                                                        <tr>
                                                            <td><?=$utilisateur['firstname'] ?> <?=$utilisateur['lastname'] ?></td>
                                                
                                                            <td><?=$utilisateur['phone_number'] ?></td>
                                                            <td><?=$utilisateur['email'] ?></td>
                                                            <td>
                                                                <?php if($utilisateur['is_active_flag'] == 1): ?>
                                                                    <span class="btn ripple btn-success btn-rounded">Activer</span>
                                                                <?php endif; ?>
                                                                <?php if($utilisateur['is_active_flag'] == 0): ?>
                                                                    <span class="btn ripple btn-danger btn-rounded">Inactiver</span>
                                                                <?php endif; ?>
                                                                
                                                            </td>
                                                            <td >
                                                                <?php if($utilisateur['is_active_flag'] == 1): ?>
                                                                    <button onclick="document.location='<?php $lib->customerSite ?>/utilisateurs/bloquer/<?=$utilisateur['user_id']?>'" class="btn ripple btn-danger">Réactiver</button>
                                                                <?php endif; ?>
                                                                <?php if($utilisateur['is_active_flag'] == 0): ?>
                                                                    <button onclick="document.location='<?php $lib->customerSite ?>/utilisateurs/activer/<?=$utilisateur['user_id']?>'" class="btn ripple btn-success">Activer</button>
                                                                <?php endif; ?>
                                                                <span onclick="document.location='<?php $lib->customerSite ?>/utilisateurs/password/<?=$utilisateur['user_id']?>'" class="btn ripple btn-primary">Modifier le mot de passe</span>
                                                                <button onclick="document.location='<?php $lib->customerSite ?>/utilisateurs/modifier/<?=$utilisateur['user_id'] ?>'" class="btn ripple btn-info">Modifier</button>
                                                            </td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                <?php endif;?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->    
        </div>
    </div>
</div>
<!-- End Main Content-->