
			<!-- Main Content-->
			<div class="main-content side-content pt-0">

				<div class="container-fluid">
					<div class="inner-body">
<!-- Page Header -->
                    <div class="page-header">
							<div>
								<h2 class="main-content-title tx-24 mg-b-5">Code USSD</h2>
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
									
								</ol>
                                <div class="d-flex">
								<div class="justify-content-center">
									
                                    <button type="button" onclick="document.location='<?php $lib->customerSite ?>/configurations/ussd/ajouter'" class="btn btn-info my-2 btn-lg">
                                        Ajouter une nouvelle code USSD
                                        </button>
								</div>
							</div>
							</div>
						</div>

						
						
						<!-- End Page Header -->

						
                        

						<!-- Row -->
						<div class="row row-sm">
							<div class="col-lg-12">
								<div class="card custom-card">
									<div class="card-body">
										<div>
											<h6 class="main-content-label mb-1">Liste des offres</h6>
										</div>
										<div class="table-responsive">
											<table class="table table-striped" id="example1">
												<thead>
                                                    <tr>
                                                        <th>Code ussd</th>
                                                        <th>Catégories</th>
                                                        <th>Opérations</th>
                                                        <th>Réseaux télécoms</th>
                                                        <th>Actions</th>
                                                    </tr>
												</thead>
												<tbody>
                                                    <?php if(!empty($data['ussd'])): ?>
                                                        <?php foreach($data['ussd'] as $ussd): ?>
                                                        <tr>
                                                            <td><?=$ussd['ussd_code'] ?></td>
                                                            <td><?=$ussd['libelle'] ?></td>
                                                            <td><?=$ussd['type'] ?></td> 
                                                            <td><?= $ussd['network_operator_name'] ?></td>                                   
                                                            <td>
                                                                <span onclick="document.location='<?php $lib->customerSite ?>/configurations/ussd/modifier/<?=$ussd['category_ussd_id'] ?>'" class="btn btn-primary ">Modifier</span>
                                                            </td>
                                                        </tr>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- End Row -->



