<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>

<?php include _VIEW_PATH."common_side_bar.phtml"; ?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>


    <!-- Main Content-->
			<div class="main-content side-content pt-0">

                <div class="container-fluid">
                    <div class="inner-body">

        <!-- Page Header -->
                    <div class="page-header">

                            <?php include _VIEW_PATH."common_top_for_dashboard_content.phtml"; ?>
                    </div>

                    <form action="" method="post">
                        <div class="row row-sm">
							<div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
										<div>
											<h6 class="main-content-label mb-1">Attribuer une licence</h6>
											<!-- <p class="text-muted card-sub-title">A basic form control input and textarea with disabled and readonly mode.</p> -->
										</div>
										<div class="row row-sm">
                                        <div class="form-group col-lg">
											<select name="agent" class="form-control select2">
                                                <option selected>Selectionner un Agent</option>
                                                <?php if(isset($response)): ?>
                                                    <?php foreach($response as $agent): ?>
                                                        <option value="<?=$agent['user_id'] ?>"><?=$agent['firstname'] .' '. $agent['lastname'] ?></option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
											</select>
										</div>
											<div class="col-lg mg-t-10 mg-lg-t-0">
												<input class="form-control" disabled placeholder="Input box (disabled)" value="<?=$response1['licence_key'] ?>" name="licence" type="text">
											</div>
                                            <div class="col-12 mt-2">
                                                <button type="submit" class="btn btn-primary" name="soumettre">Attribuer</button>
                                            </div>
										</div>
									</div>
								</div>
							</div>
                        
						</div>
                        </form>
                    </div>
                </div>
            </div>
      

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>
