<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>


<?php include _VIEW_PATH."common_side_bar.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>


<div class="main-content side-content pt-0">

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
							<div>
								<h2 class="main-content-title tx-24 mg-b-5">Création de nouvelle licence</h2>
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
									<li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[2];?></li>
								</ol>
							</div>
							
						</div>
						<!-- End Page Header -->

						<!-- Row -->
						<div class="row row-sm">
							<div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
										<form action="" method="post" id="form">
                                            <div id="wizard1">
                                                <h3>Companie</h3>
                                                <section class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <p class="mg-b-10">Désignation</p>
                                                            <input type="text" class="form-control" name="nomCompanie" id="" value="">
                                                        </div>
                                                        <div class="form-group">
                                                            <p class="mg-b-10">N° RCCM</p>
                                                            <input type="text" class="form-control" name="rccm" id="" value="">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <p class="mg-b-10">N° IFU</p>
                                                            <input type="text" class="form-control" name="ifu" id="" value="">
                                                        </div>
                                                        <div class="form-group">
                                                            <p class="mg-b-10">Token</p>
                                                            <input type="text" class="form-control" name="token" id="" value="">
                                                        </div>
                                                        
                                                    </div>
                                                </section>
                                                <h3>Addresse</h3>
                                                <section class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <p class="mg-b-10">Addresse</p>
                                                            <input type="text" class="form-control" required name="addresse" id="addresse" value="">
                                                        </div>
                                                        <div class="form-group">
                                                            <p class="mg-b-10">Code postal</p>
                                                            <input type="text" class="form-control" required name="postal" id="postal" value="">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <p class="mg-b-10">Ville</p>
                                                            <input type="text" class="form-control" required name="ville" id="ville" value="" >
                                                        </div>
                                                        <div class="form-group">
                                                            <p class="mg-b-10">Pays</p>
                                                            <select required name="country" id="country" class="form-control select2">
                                                                <option selected>Séléctionner un pays</option>
                                                                <?php if(isset($data['country'])): ?>
                                                                    <?php foreach($data['country'] as $country): ?>
                                                                        <option value="<?=$country['country_id'] ?>"><?=$country['description'] ?></option>
                                                                    <?php endforeach; ?>
                                                                <?php endif; ?>
                                                            </select>
                                                        </div>
                                                        
                                                    </div>
                                                </section>
                                                <h3>Manager</h3>
                                                <section class="row">
                                                        <div class="col-md-6">
                                                            <div class="form-group">
                                                                <p class="mg-b-10">Nom</p>
                                                                <input type="text" class="form-control" id="nom" required name="nom" placeholder="Nom">
                                                            </div>
                                                            <div class="form-group">
                                                                <p class="mg-b-10">Prénoms</p>
                                                                <input type="text" class="form-control" id="prenom" required name="prenom"  placeholder="Prénoms">
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <div class="form-group">
                                                                <p class="mg-b-10">Téléphone</p>
                                                                <input type="text" class="form-control" id="phone" required name="phone" placeholder="Téléphone">
                                                            </div>
                                                            <div class="form-group">
                                                                <p class="mg-b-10">Date d'expiration</p>
                                                                <input type="date" class="form-control" id="expiration" required name="expiration" >
                                                            </div>
                                                        
                                                        </div>
                                                        
                                                        <div class="col-md-6">
                                                            <div class="form-group">
                                                                <p class="mg-b-10">Mot de passe</p>
                                                                <input type="text" class="form-control" id="password" required name="password" placeholder="Mot de passe">
                                                            </div>
                                                            <div class="form-group">
                                                                <p class="mg-b-10">Réécrire le mot de passe</p>
                                                                <input type="text" class="form-control" id="confirmer" required name="confirmer" placeholder="Mot de passe">
                                                            </div>
                                                        
                                                        </div>
                                                </section>
                                                <h3>Offre</h3>
                                                <section class="row">
                                                <div class="col-md-12 col-lg-12 col-xl-12">
                                                    <div class="">
                                                        <div class="row">
                                                            <div class="col-sm-6 form-group">
                                                                <label class="">Licence key</label>
                                                                <input class="form-control" readonly type="text" value="<?php echo $licenceKey ?>">
                                                                <input class="form-input" type="text" hidden name="licence_key" id="licence_key" value="<?php echo $licenceKey ?>">
                                                            </div>
                                                            <div class="col-sm-6 form-group">
                                                                <label class="">Expiration</label>
                                                                <div class="pos-relative">
                                                                    <input class="form-control pd-r-80" name="licence_fin" required="" type="date">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="form-group">
                                                            <div class="row row-sm">
                                                                <div class="col-sm-6">
                                                                    <label class="">Type offres</label>
                                                                    <select class="form-control select select2 " name="licence_type">
                                                                        <option > Sélectionner une offre</option>
                                                                        <?php if(isset($data['type'])): ?>
                                                                            <?php foreach($data['type'] as $type): ?>
                                                                                <option value="<?=$type['licence_type_id'] ?>"><?=$type['licence_type_name'] ?></option>
                                                                            <?php endforeach; ?>
                                                                        <?php endif; ?>
                                                                    </select>
                                                                </div>
                                                                <div class="col-sm-6 mg-t-20 mg-sm-t-0">
                                                                    <label class="">Services</label>
                                                                    <select class="form-control select2 " name=services[] multiple="multiple" >
                                                                        <option> Sélectionner des services</option>
                                                                        <?php if(isset($data['services'])): ?>
                                                                            <?php foreach($data['services'] as $service): ?>
                                                                                <option value="<?=$service['service_id'] ?>"><?=$service['libelle'] ?></option>
                                                                            <?php endforeach; ?>
                                                                        <?php endif; ?>
                                                                    </select>
                                                                </div>
                                                                
                                                                </div>
                                                            </div>
                                                        </div>                                                        
                                                    </div>
                                                </div>
                                                </section>
                                            </div>
                                        </form>
									</div>
								</div>
							</div>
						</div>

						
						
					</div>
				</div>
			</div>

	

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>

<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>