<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>

<?php include _VIEW_PATH."common_side_bar.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

<?php if($url_array[2] == "ajouter"):?>
<div class="main-content side-content pt-0">
<?php if(isset($notification)):?>
    <div class="alert alert-danger mb-0" role="alert">
        <span class="alert-inner--icon"><i class="fe fe-slash"></i></span>
        <span class="alert-inner--text"><?php echo $notification ?></span>
    </div>                                           
<?php endif;?>

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
                            <div>
                                <h2 class="main-content-title tx-24 mg-b-5">Création un nouveau manager</h2>
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
                                        <li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[2];?></li>
                                    </ol>
                                                
                            </div>
                        </div>
						<!-- End Page Header -->
						<!-- Row -->
					    <div class="row row-sm">
                        <div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
                                    <form action="ajouter" method="post">
                                        <div class="row row-sm">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Nom</p>
                                                    <input type="text" class="form-control" required name="nom" id="nom" value="">
                                                    <?php if(isset($message)):?>
                                                        <span class="text-danger"><?php echo $message ?></span>
                                                    <?php endif;?>
                                                </div>
                                                <div class="form-group">
                                                    <p class="mg-b-10">Prénoms</p>
                                                    <input type="text" class="form-control" name="prenom" id="prenom" value="">
                                                                    
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Email</p>
                                                    <input type="text" class="form-control" require name="email" id="email" value="">
                                                                    
                                                </div>      
                                                <div class="form-group">
                                                    <p class="mg-b-10">Téléphone</p>
                                                    <input type="text" class="form-control" require name="phone" id="phone" value="">
                                                    <?php if(isset($message)):?>
                                                        <span class="notification"><?php echo $message ?></span>
                                                    <?php endif;?>                
                                                </div>                                                   
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Mot de passe</p>
                                                    <input type="text" class="form-control" require name="password" id="password" value="">
                                                                    
                                                </div>      
                                                <div class="form-group">
                                                    <p class="mg-b-10">Confirmer mot de passe</p>
                                                    <input type="text" class="form-control" require name="confirmer" id="confirmer" value="">
                                                    <?php if(isset($messagepassword)):?>
                                                        <span class="notification"><?php echo $messagepassword ?></span>
                                                    <?php endif;?>           
                                                </div>                                                   
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Marchand</p>
                                                    <select required name="companie" id="companie" class="form-control select2">
                                                        <option selected>Séléctionner un marchand</option>
                                                        <?php if(isset($data['company'])): ?>
                                                            <?php foreach($data['company'] as $company): ?>
                                                                <option value="<?=$company['company_id'] ?>"><?=$company['company_name'] ?></option>
                                                            <?php endforeach; ?>
                                                        <?php endif; ?>
                                                    </select>
                                                </div>  
                                                <div class="form-group">
                                                    <p class="mg-b-10">Addresse</p>
                                                    <select required name="addresse" id="addresse" class="form-control select2">
                                                        <option selected>Séléctionner un addresse</option>
                                                        <?php if(isset($data['addresses'])): ?>
                                                            <?php foreach($data['addresses'] as $addresse): ?>
                                                                <option value="<?=$addresse['address_id'] ?>"><?=$addresse['postal_address'] ?></option>
                                                            <?php endforeach; ?>
                                                        <?php endif; ?>
                                                    </select>
                                                </div>                                                  
                                            </div>
                                            <input type="text" hidden name="type" value="1">
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn ripple btn-info" name="soumettre">Créer le manager</button>
                                        </div>
                                    </form>
									</div>
								</div>
							</div>
						</div>
<?php else:?>
    <div class="main-content side-content pt-0">
<?php if(isset($notification)):?>
    <div class="alert alert-danger mb-0" role="alert">
        <span class="alert-inner--icon"><i class="fe fe-slash"></i></span>
        <span class="alert-inner--text"><?php echo $notification ?></span>
    </div>                                           
<?php endif;?>

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
                            <div>
                                <h2 class="main-content-title tx-24 mg-b-5">Création un nouveau agent</h2>
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
                                        <li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[2];?></li>
                                        <li class="breadcrumb-item active" aria-current="page"><?= $url_array[3] ?></li>
                                    </ol>
                                                
                            </div>
                        </div>
						<!-- End Page Header -->
						<!-- Row -->
					    <div class="row row-sm">
                        <div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
                                    <form action="" method="post">
                                        <div class="row row-sm">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Nom</p>
                                                    <input type="text" class="form-control" required name="nom" id="nom" value="">
                                                    <input type="hidden" name="company" value="<?php echo $url_array[4] ?>">
                                                    <?php if(isset($message)):?>
                                                        <span class="text-danger"><?php echo $message ?></span>
                                                    <?php endif;?>
                                                </div>
                                                <div class="form-group">
                                                    <p class="mg-b-10">Prénoms</p>
                                                    <input type="text" class="form-control" name="prenom" id="prenom" value="">
                                                                    
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Email</p>
                                                    <input type="text" class="form-control" require name="email" id="email" value="">
                                                                    
                                                </div>      
                                                <div class="form-group">
                                                    <p class="mg-b-10">Téléphone</p>
                                                    <input type="text" class="form-control" require name="phone" id="phone" value="">
                                                    <?php if(isset($message)):?>
                                                        <span class="notification"><?php echo $message ?></span>
                                                    <?php endif;?>                
                                                </div>                                                   
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Mot de passe</p>
                                                    <input type="text" class="form-control" require name="password" id="password" value="">
                                                                    
                                                </div>      
                                                                                               
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <p class="mg-b-10">Confirmer mot de passe</p>
                                                    <input type="text" class="form-control" require name="confirmer" id="confirmer" value="">
                                                    <?php if(isset($messagepassword)):?>
                                                        <span class="notification"><?php echo $messagepassword ?></span>
                                                    <?php endif;?>           
                                                </div> 
                                            </div>
                                            <input type="text" hidden name="type" value="1">
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn ripple btn-info" name="agent">Créer l'agent</button>
                                        </div>
                                    </form>
									</div>
								</div>
							</div>
						</div>
<?php endif;?>
<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>