<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>


<?php include _VIEW_PATH."common_side_bar.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

<div class="main-content side-content pt-0">
<?php if(isset($notification)):?>
    <div class="alert alert-danger mb-0" role="alert">
        <span class="alert-inner--icon"><i class="fe fe-slash"></i></span>
        <span class="alert-inner--text"><?php echo $notification ?></span>
    </div>                                           
<?php endif;?>

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
							<div>
								<h2 class="main-content-title tx-24 mg-b-5">Création d'une nouvelle offre</h2>
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
									<li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[2];?></li>
								</ol>
                                
							</div>
						</div>
						<!-- End Page Header -->

						
                        

						<!-- Row -->
					    <div class="row row-sm">
                        <div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
										<form action="addType" method="post">
                                            <div class="row row-sm">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Libellé de l'offre</p>
                                                        <input type="text" class="form-control" require name="libelle" id="" value="">
                                                        <?php if(isset($message1)):?>
                                                            <span class="text-danger"><?php echo $message1 ?></span>
                                                        <?php endif;?>
                                                    </div>
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Nombre d'équipement autorisés</p>
                                                        <input type="text" class="form-control" require name="equipement" id="" value="">
                                                        <?php if(isset($message2)):?>
                                                            <span class="text-danger"><?php echo $message2 ?></span>
                                                        <?php endif;?>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Nombre de transaction autorisés / jour</p>
                                                        <input type="text" class="form-control" require name="transaction" id="" value="">
                                                        <?php if(isset($message3)):?>
                                                            <span class="notification"><?php echo $message3 ?></span>
                                                        <?php endif;?>
                                                    </div>                                                    
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn ripple btn-info" name="soumettre">Créer l'offre</button>
                                            </div>
                                        </form>
									</div>
								</div>
							</div>
						</div>
<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>