
<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>

<?php include _VIEW_PATH."common_side_bar.phtml"; ?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

	<!-- <main>
        <div>
            <span class="main-title font-1">Création un nouveau utilisateur</span>
            <div class="track">
                <span <?php if($page_requested =="administration"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $url_array[2];?></span><span>/</span><span>Création</span>
            </div>
            <div class="form">
                <form class="row g-3" action="" method="post">
                <div class="col-md-6">
                    <label for="nom" class="form-label">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom">
                </div>
                <div class="col-md-6">
                    <label for="prenom" class="form-label">Prénoms</label>
                    <input type="text" class="form-control" id="prenom" name="prenom"  placeholder="Prénoms">
                </div>
                
                <div class="col-md-6">
                    <label for="phone" class="form-label">Téléphone</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Téléphone">
                    <?php if(isset($message)):?>
                        <span class="notification"><?php echo $message ?></span>
                    <?php endif;?>
                </div>
                <div class="col-md-6">
                    <label for="password" class="form-label">Mot de passe</label>
                    <input type="text" class="form-control" id="password" name="password" placeholder="Mot de passe">
                </div>
                <div class="col-md-6">
                    <label for="confirmer" class="form-label">Réécrire le mot de passe</label>
                    <input type="text" class="form-control" id="confirmer" name="confirmer" placeholder="Mot de passe">
                    <?php if(isset($messagepassword)):?>
                        <span class="notification"><?php echo $messagepassword ?></span>
                    <?php endif;?>
                </div>
                <div class="col-md-6">
                    <label for="password" class="form-label">Application UUID</label>
                    <input type="text" class="form-control" id="password" name="uuid" placeholder="L'application uuid">
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary" name="soumettre">Créer un utilisateur</button>
                </div>
                </form>
            </div>
        </div>
    </main> -->

    <!-- Main Content-->
			<div class="main-content side-content pt-0">

<div class="container-fluid">
    <div class="inner-body">

<!-- Page Header -->
    <div class="page-header">

            <?php include _VIEW_PATH."common_top_for_dashboard_content.phtml"; ?>
    </div>

    <form action="" method="post">
        <div class="row row-sm">
            <div class="col-lg-12 col-md-12">
                <div class="card custom-card">
                    <div class="card-body">
                        <div>
                            <h6 class="main-content-label mb-1">Création un nouveau utilisateur</h6>
                            <!-- <p class="text-muted card-sub-title">A basic form control input and textarea with disabled and readonly mode.</p> -->
                        </div>
                        <div class="row row-sm">
                            <div class="col-lg-6 mg-t-10 mg-lg-t-0 mt-4">
                                <input class="form-control"   placeholder="nom" value="" name="nom" type="text">
                            </div>
                            <div class="col-lg-6 mg-t-10 mg-lg-t-0 mt-4">
                                <input class="form-control"  placeholder="prenom" value="" name="prenom" type="text">
                            </div>
                            <div class="col-lg-6 mg-t-10 mg-lg-t-0 mt-4">
                                <input class="form-control"  placeholder="phone" value="" name="phone" type="text">
                                <?php if(isset($message)):?>
                                    <span class="notification"><?php echo $message ?></span>
                                <?php endif;?>
                            </div>
                            <div class="col-lg-6 mg-t-10 mg-lg-t-0 mt-4">
                                <input class="form-control"  placeholder="mot de passe" value="" name="password" type="text">
                            </div>
                            <div class="col-lg-6 mg-t-10 mg-lg-t-0 mt-4">
                                <input class="form-control"  placeholder="Confirmer le mot de passe" value="" name="confirmer" type="text">
                                <?php if(isset($messagepassword)):?>
                                    <span class="notification"><?php echo $messagepassword ?></span>
                                <?php endif;?>
                            </div>
                            <div class="col-lg-6 mg-t-10 mg-lg-t-0 mt-4">
                                <input class="form-control"  placeholder="uuid" value="" name="uuid" type="text">
                            </div>
                            <div class="col-12 mt-2">
                                <button type="submit" class="btn btn-primary" name="soumettre">Attribuer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
        </form>
    </div>
</div>
</div>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>