<?php include _VIEW_PATH."/common_header.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

	<main>
        <div>
            <span class="main-title font-1">Création un nouveau utilisateur</span>
            <div class="track">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $url_array[2];?></span><span>
            </div>
            <div class="form">
                <!--<form action="ajouter" method="post">
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="licence">Nom</label>
                            <input class="form-input" type="text" name="libelle" id="" value="" >
                            <?php if(isset($message)):?>
                                <span class="notification"><?php echo $message ?></span>
                            <?php endif;?>
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="postal">Prénoms</label>
                            <input class="form-input" type="text" name="postal" id="" value="">
                        </div>
                        
                    </div>
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="ville">Email</label>
                            <input class="form-input" type="text" name="ville" id="" value="" >
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="ville">Téléphone</label>
                            <input class="form-input" type="text" name="ville" id="" value="" >
                            <?php if(isset($messageCountry)):?>
                                <span class="notification"><?php echo $messageCountry ?></span>
                            <?php endif;?>
                        </div>
                        
                    </div>
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="ville">Date d'expiration</label>
                            <input class="form-input" type="text" name="ville" id="" value="" >
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="ville">Reécrire le mots de passe</label>
                            <input class="form-input" type="text" name="ville" id="" value="" >
                            <?php if(isset($messageCountry)):?>
                                <span class="notification"><?php echo $messageCountry ?></span>
                            <?php endif;?>
                        </div>
                        
                    </div>
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="ville">Mots de passe</label>
                            <input class="form-input" type="text" name="ville" id="" value="" >
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="ville">Reécrire le mots de passe</label>
                            <input class="form-input" type="text" name="ville" id="" value="" >
                            <?php if(isset($messageCountry)):?>
                                <span class="notification"><?php echo $messageCountry ?></span>
                            <?php endif;?>
                        </div>
                        
                    </div>
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="societe">Companies</label>
                            <select class="form-select margin-bottom-20" name="societe" id="societe">
                                <option value="">Sélectionne une compagnie</option>
                                <?php if(isset($data['company'])): ?>
                                    <?php foreach($data['company'] as $company): ?>
                                        <option value="<?=$company['company_id'] ?>"><?=$company['company_name'] ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                            <?php if(isset($messageCompany)):?>
                                <span class="notification"><?php echo $messageCompany ?></span>
                            <?php endif;?>
                        </div>

                        <div class="input-form margin-bottom-20">
                            <label for="societe">Addresse</label>
                            <select class="form-select margin-bottom-20" name="societe" id="societe">
                                <option value="">Sélectionne une addresse</option>
                                <?php if(isset($data['company'])): ?>
                                    <?php foreach($data['company'] as $company): ?>
                                        <option value="<?=$company['company_id'] ?>"><?=$company['company_name'] ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                            <?php if(isset($messageCompany)):?>
                                <span class="notification"><?php echo $messageCompany ?></span>
                            <?php endif;?>
                        </div>
                        
                    </div>
                    <div class="margin-bottom-20">
                        <button class="form-button" name="soumettre" type="submit">CREER UN MANAGER</button>
                    </div>
                </form>-->
                <form class="row g-3" action="" method="post">
                <div class="col-md-6">
                    <label for="nom" class="form-label">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom">
                </div>
                <div class="col-md-6">
                    <label for="prenom" class="form-label">Prénoms</label>
                    <input type="text" class="form-control" id="prenom" name="prenom"  placeholder="Prénoms">
                </div>
                <div class="col-md-6">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                </div>
                <div class="col-md-6">
                    <label for="phone" class="form-label">Téléphone</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Téléphone">
                    <?php if(isset($message)):?>
                        <span class="notification"><?php echo $message ?></span>
                    <?php endif;?>
                </div>
                <div class="col-md-6">
                    <label for="password" class="form-label">Mot de passe</label>
                    <input type="text" class="form-control" id="password" name="password" placeholder="Mot de passe">
                </div>
                <div class="col-md-6">
                    <label for="confirmer" class="form-label">Réécrire le mot de passe</label>
                    <input type="text" class="form-control" id="confirmer" name="confirmer" placeholder="Mot de passe">
                    <?php if(isset($messagepassword)):?>
                        <span class="notification"><?php echo $messagepassword ?></span>
                    <?php endif;?>
                </div>
                <div class="col-md-3">
                    <label for="expiration" class="form-label">Date d'expiration</label>
                    <input type="date" class="form-control" name="expiration"  id="expiration">
                </div>
                <div class="col-md-3">
                    <label for="uuid" class="form-label">Application uuid</label>
                    <input type="text" class="form-control" name="uuid"  id="uuid" placeholder="Application uuid">
                    <?php if(isset($messageuuid)):?>
                        <span class="notification"><?php echo $messageuuid ?></span>
                    <?php endif;?>
                </div>
                
                <div class="col-md-3">
                    <label for="type" class="form-label">Type</label>
                    <select id="type" class="form-select" name="type">
                        <option selected>Selectionner un type</option>
                        <option value="0">Administrateur</option>
                        <option value="1">Support</option>
                        <option value="1">Facturation</option>
                        <option value="1">Vente</option>
                    </select>
                </div>
                <div class="col-12">
                    <div class="form-check">
                    <input class="form-check-input" type="checkbox" checked name="activer" id="gridCheck">
                    <label class="form-check-label" for="gridCheck">
                        Activer
                    </label>
                    </div>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary" name="soumettre">Créer un utilisateur</button>
                </div>
                </form>
            </div>
        </div>
    </main>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>