<?php include _VIEW_PATH."/common_header.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

	<main>
        <div>
            <span class="main-title font-1">Modifier un type de licence</span>
            <div class="track">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $url_array[2];?></span><span>/</span><span><?php echo $url_array[3];?></span>
            </div>
            <div class="form">
                <form action="" method="post">
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="libelle">Libellé du type</label>
                            <input class="form-input" type="text" name="libelle" id="" value="<?php echo $data['type']['licence_type_name'] ?>" >
                            <?php if(isset($message)):?>
                                <span class="notification"><?php echo $message ?></span>
                            <?php endif;?>
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="equipement">Nombre d'équipement autorisés</label>
                            <input class="form-input" type="text" name="equipement" id="" value="<?php echo $data['type']['licence_nb_equipment'] ?>">
                            <?php if(isset($message)):?>
                                <span class="notification"><?php echo $message ?></span>
                            <?php endif;?>
                        </div>
                        
                    </div>
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="transaction">Nombre de transaction autorisés / jour</label>
                            <input class="form-input" type="text" name="transaction" id="" value="<?php echo $data['type']['licence_nb_transactions_day'] ?>" >
                            <?php if(isset($message)):?>
                                <span class="notification"><?php echo $message ?></span>
                            <?php endif;?>
                        </div>
                        
                    </div>
                    <div class="margin-bottom-20">
                        <button class="form-button" name="soumettre" type="submit">MODIFIER LE TYPE</button>
                    </div>
                </form>
            </div>
        </div>
    </main>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>