<?php include _VIEW_PATH."/common_header.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

	<main>
        <div>
            <span class="main-title font-1">Modifier la licence</span>
            <div class="track">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $url_array[2];?></span><span>/</span><span><?php echo $url_array[3];?></span>
            </div>
            <div class="form">
                <form action="addLicence" method="post">
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="licence">Licence Key</label>
                            <input class="form-input" type="text" name="licence" id="" value="<?php echo $licence['licence_key'] ?>" disabled>
                            <input class="form-input" type="text" hidden name="licence_key" id="" value="<?php echo $licence['licence_key'] ?>">
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="licence">Expiration de la licence</label>
                            <input class="form-input" type="date" name="licence_fin" value="<?php echo $expiration->format('Y-m-d') ?>" id="" placeholder="Entrer la licence key">
                        </div>
                        
                    </div>
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="licence">Début de la licence</label>
                            <input class="form-input" type="date" name="licence_debut" disabled id="" min="<?php echo date("Y-m-d") ?>" value="<?php echo date("Y-m-d") ?>">
                        </div>
                        
                    </div>
                    <div class="form-check margin-bottom-20 form-content">
                        <div>
                            <div>
                                <label class="margin-right" for="actif">Actif</label>
                                <input type="checkbox" name="actif" <?php if($licence['is_active'] == 1) echo 'checked'?> value="" id="">
                            </div>
                            <div>
                                <label class="margin-right" for="equipement">Equipement</label>
                                <input type="checkbox" <?php if($licence['is_for_equipement_flag'] == 1) echo 'checked'?> name="equipement" id="">
                            </div>
                        </div>
                        <div class="input-form" style="align-items:end">
                            <label for="">Application uuid</label>
                            <input class="form-input" style="width:100%" type="text" name="application" value="<?php echo $licence['application_uuid'] ?>" id="" placeholder="Entrer l'id de l'application" >
                        </div>
                    </div>
                    <div class="form-content">                        
                        <div class="input-form" style="margin-right:20px">
                            <label for="societe">Services</label>
                            <select class="form-select margin-bottom-20" name="services[]" id="select" multiple>
                                <?php if(isset($data['services'])): ?>
                                    <?php foreach($data['services'] as $service): ?>
                                        <option value="<?=$service['service_id'] ?>" <?php echo in_array($service['service_id'],$service_array) ? 'selected':'' ?>><?=$service['libelle'] ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                        </div>
                        <!--<div class="input-form" style="align-items:end">
                            <label for="">Token</label>
                            <input class="form-input" style="width:100%" type="text" name="token" id="" placeholder="Entrer le token de la compagnie" >
                        </div>-->
                        
                    </div>
                    <div class="margin-bottom-20" style="margin-top:20px">
                        <button class="form-button" name="soumettre" type="submit">MODIFIER LA LICENCE</button>
                    </div>
                </form>
            </div>
        </div>
    </main>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>