<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>


<?php include _VIEW_PATH."common_side_bar.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>


			<!-- Main Content-->
			<div class="main-content side-content pt-0">

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
							<div>
								<h2 class="main-content-title tx-24 mg-b-5">Modification d'un marchand</h2>
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
									<li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[2];?></li>
								</ol>
                                
							</div>
						</div>
						<!-- End Page Header -->

						
                        

						<!-- Row -->
					    <div class="row row-sm">
                        <div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
										<form action="" method="post">
                                            <div class="row row-sm">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Désignation</p>
                                                        <input type="text" class="form-control" name="libelle" id="" value="<?php echo $data['services']['company_name'] ?>">
                                                    </div>
                                                    <div class="form-group">
                                                        <p class="mg-b-10">N° RCCM</p>
                                                        <input type="text" class="form-control" name="rccm" id="" value="<?php echo $data['services']['company_number'] ?>">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">N° IFU</p>
                                                        <input type="text" class="form-control" name="ifu" id="" value="<?php echo $data['services']['registration_number'] ?>">
                                                    </div>
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Token</p>
                                                        <input type="text" class="form-control" name="token" id="" value="<?php echo $data['services']['company_token'] ?>">
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <button class="btn ripple btn-info" name="soumettre">MODIFIER LE MARCHAND</button>
                                            </div>
                                        </form>
									</div>
								</div>
							</div>
						</div>
						<!-- End Row -->

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>