<?php include _VIEW_PATH."/common_header.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

	<main>
        <div>
            <span class="main-title font-1">Modifier le mot de passe</span>
            <div class="track">
                <span <?php if($page_requested =="administration"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $url_array[2];?></span><span>/</span><span><?php echo $url_array[3];?></span>
            </div>
            <div class="form">
                <form class="row g-3" action="" method="post">
                
                <div class="col-md-6">
                    <label for="password" class="form-label">Mot de passe</label>
                    <input type="password" class="form-control" id="password" name="password" value="" placeholder="Entrer le nouveau mot de passe">
                </div>
                <div class="col-md-6">
                    <label for="confirmer" class="form-label">Réécrire le mot de passe</label>
                    <input type="password" class="form-control" id="confirmer" name="confirmer" value="" placeholder="Réecrire le mot de passe">
                    <?php if(isset($messagepassword)):?>
                        <span class="notification"><?php echo $messagepassword ?></span>
                    <?php endif;?>
                </div>
                
                <div class="col-12">
                    <button type="submit" class="btn btn-primary" name="update">Modifier le mot de passe</button>
                </div>
                </form>
            </div>
        </div>
    </main>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>