<?php include _VIEW_PATH."/common_header_dashboard.phtml";?>


<?php include _VIEW_PATH."common_side_bar.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

<div class="main-content side-content pt-0">
<?php if(isset($notification)):?>
    <div class="alert alert-danger mb-0" role="alert">
        <span class="alert-inner--icon"><i class="fe fe-slash"></i></span>
        <span class="alert-inner--text"><?php echo $notification ?></span>
    </div>                                           
<?php endif;?>

				<div class="container-fluid">
					<div class="inner-body">

						<!-- Page Header -->
						<div class="page-header">
							<div>
								<h2 class="main-content-title tx-24 mg-b-5">Modifier une addresse</h2>
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="#"><?php echo $page_requested;?></a></li>
									<li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[2];?></li>
                                    <li class="breadcrumb-item active" aria-current="page"><?php echo $url_array[3];?></li>
								</ol>
                                
							</div>
						</div>
						<!-- End Page Header -->
						<!-- Row -->
					    <div class="row row-sm">
                        <div class="col-lg-12 col-md-12">
								<div class="card custom-card">
									<div class="card-body">
										<form action="" method="post">
                                            <div class="row row-sm">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Libellé de l'addresse</p>
                                                        <input type="text" class="form-control" required name="libelle" value="<?php echo $data['addresse']['postal_address'] ?>">
                                                        <?php if(isset($message)):?>
                                                            <span class="text-danger"><?php echo $message ?></span>
                                                        <?php endif;?>
                                                    </div>
                                                </div>
                                            
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Pays</p>
                                                        <select required name="country" id="country" class="form-control select2">
                                                            <option selected>Séléctionner un pays</option>
                                                            <?php if(isset($data['country'])): ?>
                                                                <?php foreach($data['country'] as $country): ?>
                                                                    <option value="<?=$country['country_id'] ?>" <?php echo in_array($country['country_id'],$pays) ? 'selected':'' ?>><?=$country['description'] ?></option>
                                                                <?php endforeach; ?>
                                                            <?php endif; ?>
                                                        </select>
                                                        <?php if(isset($messageCountry)):?>
                                                            <span class="text-danger"><?php echo $messageCountry ?></span>
                                                        <?php endif;?>
                                                    </div>                                                    
                                                </div>
                                                
                                            
                                            </div>
                                            <div class="row row-sm">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Ville</p>
                                                        <input type="text" class="form-control" required name="ville" value="<?php echo $data['addresse']['city'] ?>">
                                                        <?php if(isset($message)):?>
                                                            <span class="text-danger"><?php echo $message ?></span>
                                                        <?php endif;?>
                                                    </div>
                                                </div>
                                            
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Code postal</p>
                                                        <input type="text" class="form-control" required name="postal" value="<?php echo $data['addresse']['postal_code'] ?>">
                                                    </div>                                                    
                                                </div>
                                                
                                            
                                            </div>
                                            <div class="row row-sm">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <p class="mg-b-10">Marchand</p>
                                                        <select required name="societe" class="form-control select2">
                                                            <option selected>Séléctionner un pays</option>
                                                            <?php if(isset($data['company'])): ?>
                                                                <?php foreach($data['company'] as $company): ?>
                                                                    <option value="<?=$company['company_id'] ?>" <?php echo in_array($company['company_id'],$compagnie) ? 'selected':'' ?>><?=$company['company_name'] ?></option>
                                                                <?php endforeach; ?>
                                                            <?php endif; ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                                                        
                                            
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn ripple btn-info" name="soumettre">Modifier une addresse</button>
                                            </div>
                                        </form>
									</div>
								</div>
							</div>
						</div>
                    </div>
                </div>
            </div>
<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files_dashboard.phtml";?>