<?php include _VIEW_PATH."/common_header.phtml";?>

<?php include _VIEW_PATH."common_top_bar.phtml";?>

	<main>
        <div>
            <span class="main-title font-1">Modification du service</span>
            <div class="track">
                <span <?php if($page_requested =="configurations"){ ?> class="actives" <?php } ?>><?php echo $page_requested;?></span><span>/</span><span><?php echo $url_array[2];?></span><span>/</span><span><?php echo $url_array[3];?></span>
            </div>
            
            <div class="form">
                <form action="" method="post">
                    <div class="form-content">
                        <div class="input-form margin-bottom-20">
                            <label for="licence">Libellé du service</label>
                            <input class="form-input" type="text" name="libelle" id="" value="<?php echo $data['pays']['description'] ?>" >
                        </div>
                        
                        <div class="input-form margin-bottom-20">
                            <label for="licence">Description</label>
                            <input class="form-input" type="text" name="code" id="" value="<?php echo $data['pays']['country_short_name'] ?>">
                        </div>
                        
                    </div>
                    <div class="margin-bottom-20">
                        <button class="form-button" name="soumettre" type="submit">MODIFIER UN SERVICE</button>
                    </div>
                </form>
            </div>
        </div>
    </main>

<?php include _VIEW_PATH.$lib->lang."/common_footer.phtml";?>
<?php include _VIEW_PATH."/common_include_files.phtml";?>