<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Ajouter une societe</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Ajouter une societe</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-8">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Add a company</h3>
            </div>
            <header class="text-center mb-4">
              <div class="text-danger">
                <h6 id="error_message"></h6>
              </div>
              <div class="text-success">
                <h6 id="success_message"></h6>
              </div>
            </header>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="company_form">
              <div class="card-body">
                <div class="form-group">
                  <label for="company_name">Company name</label>
                  <input type="text" name="company_name" class="form-control" id="company_name" placeholder="Company name">
                </div>
                <div class="form-group">
                  <label for="company_zipcode">Company zipcode</label>
                  <input type="text" name="company_zipcode" class="form-control" id="company_zipcode" placeholder="00229">
                </div>
                <div class="form-group">
                  <label for="company_city">Company city</label>
                  <input type="text" name="company_city" class="form-control" id="company_city" placeholder="Paris">
                </div>
                <div class="form-group">
                  <label for="activity_area">Activity area</label>
                  <input type="text" name="activity_area" class="form-control" id="activity_area" placeholder="Software">
                </div>
                <div class="form-group">
                  <label for="company_type">Company type</label>
                  <select name="company_type" id="company_type">
                    <option value="">Select a type for the company</option>
                    <option value="public">Public</option>
                    <option value="private">Private</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="code_naf">Code NAF</label>
                  <input type="text" name="code_naf" class="form-control pull-right" id="code_naf">
                </div>

                <!-- </div> -->
                <!-- <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div> -->
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="button" id="submit_company" class="btn btn-primary pull-right">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->


        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <!-- <div class="col-md-6"> -->
        <!-- Form Element sizes -->
        <!-- <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Different Height</h3>
              </div>
              <div class="card-body">
                <input class="form-control form-control-lg" type="text" placeholder=".form-control-lg">
                <br>
                <input class="form-control" type="text" placeholder="Default input">
                <br>
                <input class="form-control form-control-sm" type="text" placeholder=".form-control-sm">
              </div> -->
        <!-- /.card-body -->
        <!-- </div> -->
        <!-- /.card -->


        <!-- /.card -->
        <!-- </div> -->
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
      <!-- </div> -->
      <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<script>
  $('#submit_company').click(function() {
    saveCompany();
  })

  function saveCompany() {
    document.getElementById('submit_company').innerHTML = "Enregistrement en cours. Veuillez patienter  ... <i class='fa fa-spinner fa-spin'></i>";


    var company_name = encodeURIComponent($("#company_name").val()); 
    var company_zipcode = encodeURIComponent($("#company_zipcode").val()); 
    var company_city = encodeURIComponent($("#company_city").val());
    var activity_area = encodeURIComponent($("#activity_area").val());
    var company_type = encodeURIComponent($("#company_type").val());
    var code_naf = encodeURIComponent($("#code_naf").val());


    // alert(code_naf)
    $.ajax({
      url: '/customer/saveNewCompany/',
      type: 'POST',
      data: {
        company_name:company_name,
        company_zipcode:company_zipcode,
        company_city:company_city,
        activity_area:activity_area,
        company_type:company_type,
        code_naf: code_naf
      },

      success: function(msg) {
        var val = msg.split('||');
        console.log(msg);
        if (val[0] == "false") {
          $("#error_message").html(val[1]);
          $("#error_message").show();
          $("#submit_company").attr("disabled", false);
          $("#submit_company").html("Enregistrer");

        } else if (val[0] == "true") {
          $("#success_message").html(val[1]);
          $("#error_message").html("");
          $("#success_message").show();
          $("#submit_company").html(val[1]).attr("disabled", true);

          rnd = Math.random();
          window.location.href = '/customer/companies/' + rnd;


        }

      },
      error: function(resultat, statut, erreur) {
        $("#error_message").html("Une erreur s'est produite. Veuillez réessayer. <i class='fa fa-stop-circle'></i>");
        console.log('Resultat : ' + resultat);
        console.log('Statut : ' + statut);
        console.log('Erreur : ' + erreur);
      }
    });

  }
</script>