<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Ajouter une mission</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Ajouter une mission</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add a mission</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form>
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Mission label</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Mission label">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Mission date</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="2021-17-05">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Select a contact</label>
                    <select>
                      <option value="">Select a contact</option>
                      <option value="">John DOE</option>
                      <option value="">Alex Piece</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Select a company</label>
                    <select>
                      <option value="">Select a company</option>
                      <option value="">Bénin TELECOM</option>
                      <option value="">APPLE</option>
                    </select>
                  </div>
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          
          </div>
          <!--/.col (left) -->
          <!-- right column -->
          <!-- <div class="col-md-6"> -->
            <!-- Form Element sizes -->
            <!-- <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Different Height</h3>
              </div>
              <div class="card-body">
                <input class="form-control form-control-lg" type="text" placeholder=".form-control-lg">
                <br>
                <input class="form-control" type="text" placeholder="Default input">
                <br>
                <input class="form-control form-control-sm" type="text" placeholder=".form-control-sm">
              </div> -->
              <!-- /.card-body -->
            <!-- </div> -->
            <!-- /.card -->

          
            <!-- /.card -->
          <!-- </div> -->
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->