<?php

$restrictedArea = true;
$dashboardActive = true;
// var_dump($_SESSION['customer']['store_code']);
if (in_array("ROLE_ENTREPRISE", (explode(" ", $_SESSION['customer']['role_contact'])))) {
    
    $nbOrders = $sqlData->getCountMagOrders($_SESSION['customer']['store_code']);
    // var_dump($nbOrders);
    // die;
    $nbOrders = $nbOrders['data'][0];

    $nbPendingOrders = $sqlData->getCountMagPendingOrders($_SESSION['customer']['store_code']);
    $nbPendingOrders = $nbPendingOrders['data'][0];

    $nbClosedOrders = $sqlData->getCountMagClosedOrders($_SESSION['customer']['store_code']);
    $nbClosedOrders = $nbClosedOrders['data'][0];

    $nbDelivredOrders = $sqlData->getCountMagDeliveredOrders($_SESSION['customer']['store_code']);
    $nbDelivredOrders = $nbDelivredOrders['data'][0];

    $nbInProgress = $sqlData->getCountMagInProgressOrders($_SESSION['customer']['store_code']);
    $nbInProgress = $nbInProgress['data'][0];

} elseif(in_array("ROLE_CLIENT", (explode(" ", $_SESSION['customer']['role_contact'])))) {
    
    $nbOrders = $sqlData->getCountOrders($_SESSION['customer']['contact_num']);
    $nbOrders = $nbOrders['data'][0];

    $nbPendingOrders = $sqlData->getCountPendingOrders($_SESSION['customer']['contact_num']);
    $nbPendingOrders = $nbPendingOrders['data'][0];

    $nbClosedOrders = $sqlData->getCountClosedOrders($_SESSION['customer']['contact_num']);
    $nbClosedOrders = $nbClosedOrders['data'][0];

    $nbDelivredOrders = $sqlData->getCountDeliveredOrders($_SESSION['customer']['contact_num']);
    $nbDelivredOrders = $nbDelivredOrders['data'][0];

    $nbInProgress = $sqlData->getCountInProgressOrders($_SESSION['customer']['contact_num']);
    $nbInProgress = $nbInProgress['data'][0];
}

include _VIEW_PATH . "/common_header.phtml"; ?>
<?php
// include _VIEW_PATH."common_top_bar.phtml";
include _VIEW_PATH . $lib->lang . "/top_menu.phtml";
?>


<!--=== Profile ===-->
<div class="container g-pt-70 g-pb-30">
    <div class="row">
        <?php
        if ($_SESSION['customer']['authValidated']) {
            include _VIEW_PATH . "/customer/profile_left_menu.phtml";
        }
        ?>

        <div class="col-lg-9 g-mb-50">
            <!--Profile Body-->
            <h2><?php echo $lang->trl('My dashboard'); ?></h2>
            <?php
            if ($iniObj->debug) {
                //  echo "<pre>";print_r($_SESSION); echo "</pre>";
            }
            ?>
            <?php echo $lang->trl('Welcome to Occazetneuf') . " " . $_SESSION['customer']['first_name'] . " " . strtoupper($_SESSION['customer']['last_name']) . " (" . $_SESSION['customer']['email_address'] . ")"; ?>
            <br /><br />

            <div class="profile-body margin-bottom-20">
                <div class="container mt-2">

                    <div class="row">

                        <div class="col-md-4 col-sm-6 item">
                            <div class="card item-card card-block">
                                <h5 class="card-title  mt-3 mb-3">Total des commandes</h5>
                                <h4 class="item-card-title text-center"><i class="material-icons"><?= $nbOrders->total; ?></i></h4>
                                <!-- <img src="https://static.pexels.com/photos/7357/startup-photos.jpg" alt="Photo of sunset"> -->

                            </div>
                        </div>
                        <div class="col-md-4 col-sm-6 item">
                            <div class="card item-card card-block">
                                <h5 class="card-title  mt-3 mb-3">Commandes en cours</h5>
                                <h4 class="item-card-title text-center"><i class="material-icons"><?= $nbPendingOrders->total ?></i></h4>

                            </div>
                        </div>
                        <div class="col-md-4 col-sm-6 item">
                            <div class="card item-card card-block">
                                <h5 class="card-title  mt-3 mb-3">Commandes en attente</h5>
                                <h4 class="item-card-title text-center"><i class="material-icons"><?= $nbInProgress->total ?></i></h4>

                            </div>
                        </div>

                    </div><br>
                    <!-- <div class="row">

                        <div class="col-md-4 col-sm-6 item">
                            <div class="card item-card card-block">
                                <h5 class="card-title  mt-3 mb-3">Nombre total de produits</h5>
                                <h4 class="item-card-title text-center"><i class="material-icons"></i></h4>

                            </div>
                        </div>



                    </div> -->

                </div>
            </div>
        </div>
    </div>
</div>
<!--=== End Profile ===-->
<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>

<?php include _VIEW_PATH . "/common_include_files.phtml"; ?>