<?php
$restrictedArea=true;
$formActive=true;
$passwordActive=true;

$menuActif = "PASSWORD";
include _VIEW_PATH."/global_header.phtml";
?>

    <!-- Header -->
    <header id="js-header" class="u-header">
        <div class="u-header__section">
            <?php include _VIEW_PATH."global_top_bar.phtml"; ?>
            <?php include _VIEW_PATH.$lib->lang."/top_menu.phtml"; ?>
        </div>
    </header>
    <!-- End Header -->

    <!-- Breadcrumbs -->
    <section class="g-bg-gray-light-v5 g-py-50">
        <div class="container">
            <div class="d-sm-flex text-center">
                <div class="align-self-center">
                    <h2 class="h3 g-font-weight-300 w-100 g-mb-10 g-mb-0--md">
                        <?php echo $lang->trl('My password');?>
                    </h2>
                </div>

                <div class="align-self-center ml-auto">
                    <ul class="u-list-inline">
                        <li class="list-inline-item g-mr-5">
                            <a class="u-link-v5 g-color-main g-color-primary--hover" href="/<?php echo $lib->lang;?>">
                                <?php echo $lang->trl('Home');?>
                            </a>
                            <i class="g-color-gray-light-v2 g-ml-5">/</i>
                        </li>
                        <li class="list-inline-item g-color-primary">
                            <span>
                                <?php echo $lang->trl('My password');?>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- End Breadcrumbs -->

    <section class="g-mb-100">
        <div class="container">
            <div class="row">

                <?php
                if($_SESSION['customer']['authValidated']) {
                    include _VIEW_PATH."/customer/left_side_bar.phtml";
                }
                ?>

                <!-- Profile Content -->
                <div class="col-lg-9">
                    <!-- Overall Statistics -->
                    <div class="col-md-12">
                        <div class="g-bg-gray-dark-v5 g-color-white g-pa-25">
                            <header class="d-flex text-uppercase g-mb-40 justify-content-center">
                                <div class="g-line-height-1 text-center">
                                    <div class="js-counter g-font-size-30 text-center" data-comma-separated="true">
                                        <?php echo $lang->trl('Change your password');?>
                                    </div>
                                    <label id='sp'></label>
                                </div>
                            </header>

                            <div class="d-flex justify-content-center g-mb-25">
                                <div class="w-100">
                                    <fieldset>
                                        <div class="row justify-content-center">
                                            <section class="col col-8">
                                                <div class="input-group g-mb-20">
                                                    <div class="input-group-prepend">
                                                        <label class="input-group-text g-bg-white" for="cPassword">
                                                            <i class="icon-prepend fa fa-unlock"></i>
                                                        </label>
                                                    </div>
                                                    <input
                                                            type="password"
                                                            name="cPassword"
                                                            id="cPassword"
                                                            class="form-control rounded-0 form-control-md"
                                                            placeholder="<?php echo $lang->trl('Current password');?>"
                                                            aria-describedby="sizing-addon2">
                                                </div>

                                                <div class="input-group g-mb-20">
                                                    <div class="input-group-prepend">
                                                        <label class="input-group-text g-bg-white" for="nPassword">
                                                            <i class="icon-prepend fa fa-lock"></i>
                                                        </label>
                                                    </div>
                                                    <input
                                                            type="password"
                                                            name="nPassword"
                                                            id="nPassword"
                                                            class="form-control rounded-0 form-control-md"
                                                            placeholder="<?php echo $lang->trl('New password');?>"
                                                            aria-describedby="sizing-addon2">
                                                </div>

                                                <div class="input-group g-mb-5">
                                                    <div class="input-group-prepend">
                                                        <label class="input-group-text g-bg-white" for="cNpassword">
                                                            <i class="icon-prepend fa fa-lock"></i>
                                                        </label>
                                                    </div>
                                                    <input
                                                            type="password"
                                                            name="cNpassword"
                                                            id="cNpassword"
                                                            class="form-control rounded-0 form-control-md"
                                                            placeholder="<?php echo $lang->trl('Confirm new password');?>"
                                                            aria-describedby="sizing-addon2">
                                                </div>
                                            </section>
                                        </div>
                                    </fieldset>
                                    <label id='sp'></label>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <button type="button" class="btn btn-dark mr-2" id="btnCancel">
                                    <i class="fa fa-ban mr-2"></i>
                                    <?php echo $lang->trl('Cancel');?>
                                </button>
                                <button class="btn btn-primary" type="button" id="btnSave">
                                    <i class="fa fa-save mr-2"></i>
                                    <?php echo $lang->trl('Save');?>
                                </button>
                                <label id='sp'></label>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Overall Statistics -->
            </div>
            <!-- End Profile Content -->
        </div>
    </section>


<?php include _VIEW_PATH.$lib->lang."/global_footer.phtml";?>

<?php include _VIEW_PATH."/global_include_files.phtml";?>