<?php

$restrictedArea = true;
$formActive = true;
$passwordActive = true;
$menuActif = "PASSWORD";

include _VIEW_PATH . "/common_header.phtml"; ?>

<div class="wrapper">

	<!-- Header -->
	<header id="js-header" class="u-header">
		<div class="u-header__section">
			<?php //include _VIEW_PATH."global_top_bar.phtml"; 
			?>
			<?php include _VIEW_PATH . $lib->lang . "/top_menu.phtml";  ?>
		</div>
	</header>
	<!-- End Header -->

	<!-- Breadcrumbs -->
	<section class="g-bg-gray-light-v5 g-py-50">
		<div class="container">
			<div class="d-sm-flex text-center">
				<div class="align-self-center">
					<h2 class="h3 g-font-weight-300 w-100 g-mb-10 g-mb-0--md">
						Mot de passe
					</h2>
				</div>

				<div class="align-self-center ml-auto">
					<ul class="u-list-inline">
						<li class="list-inline-item g-mr-5">
							<a class="u-link-v5 g-color-main g-color-primary--hover" href="/<?php echo $lib->lang; ?>">
								<?php echo $lang->trl('Home'); ?>
							</a>
							<i class="g-color-gray-light-v2 g-ml-5">/</i>
						</li>
						<li class="list-inline-item g-color-primary">
							<span>
								Nouveau mot de passe
							</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	<!-- End Breadcrumbs -->

	<!-- <section class="g-mb-100"> -->
	<div class="container">
		<div class="row">

			<?php
			if ($_SESSION['customer']['authValidated']) {
				include _VIEW_PATH . "/customer/profile_left_menu.phtml";
			}
			?>

			<!-- Profile Content -->
			<div class="col-lg-9">
				<!-- Overall Statistics -->
				<div class="col-md-12">
					<div class="g-bg-gray-dark-v5 g-color-white g-pa-25">
						<header class="d-flex text-uppercase">
							<div class="g-line-height-1">
								<div class="js-counter g-font-size-30" data-comma-separated="true">
									Modification de mot de passe
								</div>
							</div>
						</header>
					</div>
				</div>
				<div class="col-md-12 g-mt-20">
					<div class="profile-body margin-bottom-20">
						<div class="tabbable">
							<!-- <ul class="nav nav-pills justify-content-center" id="shipTab">
                                <li class="active">
                                    <a data-toggle="tab" href="#s1Tab" id="productFirstStep" class="btn btn-dark mr-1 text-uppercase g-font-size-13 g-mb-5 step" style="border-radius: unset!important;">
                                        <i class="fa fa-user mr-2"></i>
                                        <?php //echo $lang->trl('FirstStep'); 
										?> Etape 1
                                        <i class="fa fa-chevron-right ml-2 "></i>
                                    </a>
                                </li>
                                <li>
                                    <a data-toggle="tab" href="#s2Tab" class="btn btn-dark mr-1 text-uppercase g-font-size-13 g-mb-5 step" style="border-radius: unset!important;">
                                        <i class="fa fa-user" mr-2></i>
                                        <?php //echo $lang->trl('SecondStep'); 
										?>Etape 2
                                        <i class="fa fa-chevron-right ml-2 "></i>
                                    </a>
                                </li>
                                <li>
                                    <a data-toggle="tab" href="#s3Tab" class="btn btn-dark mr-1 text-uppercase g-font-size-13 g-mb-5 step" style="border-radius: unset!important;">
                                        <i class="fa fa-cog" mr-2></i>
                                        <?php //echo $lang->trl('ThirdStep'); 
										?>Etape 3
                                        <i class="fa fa-chevron-right ml-2 "></i>
                                    </a>
                                </li>
                                 <li>
                                    <a data-toggle="tab" href="#s4Tab" class="btn btn-dark mr-1 text-uppercase g-font-size-13 g-mb-5" style="border-radius: unset!important;">
                                        <i class="fa fa-eur" mr-2></i>
                                        <?php // echo $lang->trl('Fourth Step'); 
										?>
                                    </a>
                                </li> 
                                <li>
                                    <a data-toggle="tab" href="#s5Tab" class="btn btn-dark text-uppercase g-font-size-13 g-mb-5" style="border-radius: unset!important;">
                                        <i class="fa fa-check mr-2"></i>
                                        <?php // echo $lang->trl('Validate'); 
										?>
                                    </a>
                                </li> 
                            </ul> -->

							<header class="text-center mb-4">
								<div class="text-danger">
									<h6 id="error_message"></h6>
								</div>
								<div class="text-success">
									<h6 id="success_message"></h6>
								</div>

							</header>
							<form id="#sky-form4" class="sky-form">
								<input type="hidden" name="contact_num" id="contact_num" value="<?= $_SESSION['customer']['contact_num'] ?>">
								<input type='hidden' name='sent' value='1' />
								<header>
									<?php echo $lang->trl('Change your password'); ?>
								</header>

								<fieldset>
									<div class="row">
										<section class="col col-8">
											<label class="input"> <i class="icon-prepend fa fa-unlock"></i>
												<input type="password" placeholder="<?php echo $lang->trl('Current password'); ?>" class="form-control" name="cPassword" id="cPassword">
											</label>
										</section>
										<section class="col col-8">
											<label class="input"> <i class="icon-prepend fa fa-lock"></i> <input type="password" placeholder="<?php echo $lang->trl('New password'); ?>" class="form-control" name='nPassword' id='nPassword'>
											</label>
										</section>
										<section class="col col-8">
											<label class="input"> <i class="icon-prepend fa fa-lock"></i> <input type="password" placeholder="<?php echo $lang->trl('Confirm new password'); ?>" class="form-control" name='cNpassword' id='cNpassword'>
											</label>
										</section>
									</div>
								</fieldset>
								<label id='sp'></label>
								<footer>
									<button type="button" id="btnCancel" class="btn-u btn-u-default "><?php echo $lang->trl('Cancel'); ?></button>
									&nbsp;&nbsp;&nbsp;
									<button class="btn-u " id="btnSave" type="button"><?php echo $lang->trl('Save'); ?> <i class="fa fa-chevron-right"></i></button>
								</footer>
							</form>
						</div>
						<!-- End Checkout-Form -->
					</div>
					<!--/row-->
				</div>
				<!--/container-->
				<!--=== End Content Part ===-->
				<label id='sp'></label>
				<!--End Profile Body-->
			</div>
		</div>
		<!--/end row-->
	</div>
	<script>
		$(document).ready(function() {
			$('#btnSave').click(function() {
				$("#btnSave").html("Modification en cours. Veuillez patienter  ... <i class='fa fa-spinner fa-spin'></i>")
              .attr("disabled", true);
				saveNewpassword();
			})
		});

		function saveNewpassword() {
			var cPassword = encodeURIComponent($("input[name='cPassword']").val());
			var nPassword = encodeURIComponent($("input[name='nPassword']").val());
			var cNpassword = encodeURIComponent($("input[name='cNpassword']").val());
			var contact_num = encodeURIComponent($("input[name='contact_num']").val());

			// console.log($(files));

			$.ajax({
				type: "POST",
				url: "/customer/pChange/",
				data: {
					oldp: cPassword,

					np: nPassword,
					cp: cNpassword,
					contact_num: contact_num

				},
				success: function(msg) {
					var val = msg.split('||');
					//alert(val);
					if (val[0] == "false") {
						$("#error_message").html(val[1]);
						$("#error_message").show();
						$("#btnSave").attr("disabled", false);

					} else if (val[0] == "true") {
						document.getElementById("prevBtn").attr("disabled", true);
						$("#btnSave").html("Votre mot de passe a été modifié avec succès. ").attr("disabled", true);
						$("#error_message").html("");
						$("#success_message").html(val[1]);
						$("#sky-form4")[0].reset();

						setTimeout(function() {
							$("#success_message").hide();
							rnd = Math.random();

							window.location.href = '/customer/dashboard/' + rnd;
						}, 5000);

					}

				},
				error: function(resultat, statut, erreur) {
					$("#error_message").html("Une erreur s'est produite. Veuillez réessayer. <i class='fa fa-stop-circle'></i>");
					console.log('Resultat : ' + resultat);
					console.log('Statut : ' + statut);
					console.log('Erreur : ' + erreur);
				}
			});
		}
	</script>
	<!--/container-->

	<!--=== End Profile ===-->
	<?php include _VIEW_PATH . $lib->lang . "/common_footer.phtml"; ?>

</div>
<!--/wrapper-->

<?php include _VIEW_PATH . "/common_include_files.phtml"; ?>