<!-- <div id="s2Tab" class="profile-edit tab-pane fade in active"> -->
<div class="tab">

    <h3 class="card-header h5 text-center text-white g-brd-transparent rounded-0" style="background-color: #94c11c;">
        <!-- <span class="g-font-size-default g-mr-5">2. - </span> -->
        ETAPE N° 2
    </h3>

    <div class="card-block">
        <div class="row">
        <dl class="dl-horizontal col-lg-4">
                    <dd>
                        <section>
                            <label class="label_shipping input">
                                <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                                Hauteur
                            </label>
                            <input type="number" name="hauteur" id="hauteur" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir la hauteur du produit" min="0">

                        </section>
                    </dd>
                </dl>
                <dl class="dl-horizontal col-lg-4">
                    <dd>
                        <section>
                            <label class="label_shipping input">
                                <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                                Largeur
                            </label>
                            <input type="number" name="largeur" id="largeur" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir la largeur du produit" min="0">

                        </section>
                    </dd>
                </dl>
                <dl class="dl-horizontal col-lg-4">
                    <dd>
                        <section>
                            <label class="label_shipping input">
                                <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                                Poids
                            </label>
                            <input type="number" name="poids" id="poids" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir le poids du produit" min="0">

                        </section>
                    </dd>
                </dl>

            <dl class="dl-horizontal col-lg-4">
                <!-- <dd>
                        <section>
                            <label class="label_shipping input">
                                 <i class="icon-append fa fa-euro mr-2"></i> 
                                Taux de commission
                            </label>
                            <input type="number" name="taux_commission" id="taux_commission" class="form-control" placeholder="50" title="Saisir le taux de commission sur le produit" min="0">

                        </section>
                    </dd> -->
            </dl>
        </div>
        <div class="row">

            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                            Profondeur
                        </label>
                        <input type="number" name="profondeur" id="profondeur" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir la profondeur du produit" min="0">

                    </section>
                </dd>
            </dl>
            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                            Prix net du déposant
                        </label>
                        <input type="number" name="prix_net_deposant" id="prix_net_deposant" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir le prix net du déposant" min="0">

                    </section>
                </dd>
            </dl>
            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                            Taux assurance
                        </label>
                        <input type="number" name="taux_assurance" id="taux_assurance" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir le taux d'assurance du produit" min="0">

                    </section>
                </dd>
            </dl>
        </div>
        <div class="row">
            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                            Quantité minimum en stock
                        </label>
                        <input type="number" name="qte_minimum_stock" id="qte_minimum_stock" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir la quantité minimum en stock" min="0">

                    </section>
                </dd>
            </dl>
            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                            Quantité maximum en stock
                        </label>
                        <input type="number" name="qte_maximum_stock" id="qte_maximum_stock" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir la quantité maximum en stock" min="0">

                    </section>
                </dd>
            </dl>

            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <!-- <i class="icon-append fa fa-euro mr-2"></i> -->
                            Quantité stock alerte
                        </label>
                        <input type="number" name="qte_stock_alerte" id="qte_stock_alerte" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir le stock alerte" min="0">
                    </section>
                </dd>
            </dl>

        </div>

        <div class="row">
            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <i class="icon-append fa fa-euro mr-2"></i>
                            Coût d'emballage
                        </label>
                        <input type="number" name="cout_emballage" id="cout_emballage" value="<?= 0 ?>" step="0.01" min="0" class="form-control" placeholder="50" title="Saisir le co&ucirc;t emballage" min="0">

                    </section>
                </dd>
            </dl>
            <dl class="dl-horizontal col-lg-4">
                <dd>
                    <section>
                        <label class="label_shipping input">
                            <i class="icon-append fa fa-euro mr-2"></i>
                            Frais de port
                        </label>
                        <input type="number" name="frais_port" id="frais_port" step="0.01" min="0" value="<?= 0 ?>" class="form-control" placeholder="50" title="Saisir les frais de port" min="0">

                    </section>
                </dd>
            </dl>
        </div>

    </div>

</div>