<div class="tab">

    <!-- <div id="s3Tab" class="profile-edit tab-pane fade in active"> -->
    <!-- <div class="card card-outline-success rounded-0"> -->
        <h3 class="card-header h5 text-white text-center g-brd-transparent rounded-0" style="background-color: #94c11c;">
            <!-- <span class="g-font-size-default g-mr-5">3. - </span>
            Les images du produit -->ETAPE N° 3
        </h3><br>
        <br>


        <!-- <span style="color:#b7b7b7; font-family:ubantu; font-weight:bold; margin-left: 31px;">Glisser et déposer des images ici:</span> -->
        <!-- <div id="displayimage">
             <p class="DropImage"> Glissez et déposez des images ici. </p>
        </div> -->
        <div id="uploader">
            <input type="file" id="files" name="files[]" multiple="multiple" />
        </div>
    <!-- </div> -->
</div>