
<?php
if ($iniObj->debugViews) echo __FILE__;
$formActive = true;
$loginActive = true;
$carouselActive = true;
$title = "Articles neufs et occasions - Professionnel - Dépôt vente - Electroménager - Décoration - Informatique - Jeux vidéo - Son - Image - Téléphonie - Bricolage - Jardinage - Animalerie";

include _VIEW_PATH . "/common_header.phtml";
include _VIEW_PATH . $lib->lang . "/top_menu.phtml";

include _VIEW_PATH . "customer/page_login_content.phtml";

include _VIEW_PATH . $lib->lang . "/common_footer.phtml";
include _VIEW_PATH . "/common_include_files.phtml"; 
?>