<?php
  $formActive=true;
  $loginActive=true;

?>
      <!-- Breadcrumbs -->
      <section class="g-brd-bottom g-brd-gray-light-v4 g-py-30">
        <div class="container">
          <ul class="u-list-inline">
            <li class="list-inline-item g-mr-5">
                <a href="/" class="u-link-v5 g-color-text">
                  Accueil
                </a>
              <i class="g-color-gray-light-v2 g-ml-5 fa fa-angle-right"></i>
            </li>
            <li class="list-inline-item g-color-primary">
              <span>Réinitialiser mon compte</span>
            </li>
          </ul>
        </div>
      </section>
      <!-- End Breadcrumbs -->

      <!-- Reset -->
      <section class="container g-pt-10 g-pb-20">
        <div class="row justify-content-between">
          <div class="col-md-6 col-lg-5 order-lg-1 g-mb-80">
            <div class="g-brd-around g-brd-gray-light-v3 g-bg-white rounded g-px-30 g-py-50 mb-4">
              <header class="text-center mb-4">
                <h1 class="h4 g-color-black g-font-weight-400">Réinitialisation du compte </h1>
                <div class="text-danger"> <h6 id="error_message"></h6></div>
                <div class="text-success"> <h6 id="success_message"></h6></div>
              </header>

              <!-- Form -->
              <form class="g-py-15" id="sky-form" class="sky-form">
			  	      <input type='hidden' name='sent' value='1' />
                <div class="mb-4">
                  <div class="input-group g-rounded-left-3">
                    <span class="input-group-prepend g-width-45">
                      <span class="input-group-text justify-content-center w-100 g-bg-transparent g-brd-gray-light-v3 g-color-gray-dark-v5">
                        <i class="icon-finance-067 u-line-icon-pro"></i>
                      </span>
                    </span>
                    
                    <input placeholder="Code Client"
                      class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-rounded-left-0 g-rounded-right-3 g-py-15 g-px-15" 
					            type="text" name="email" id="email" >
                  </div>
                </div>

                <div class="mb-5">
                  <button type="button" id="s5ResetCustomer"
                    class="btn btn-block u-btn-primary g-font-size-12 text-uppercase g-py-12 g-px-25"
                    >Réinitialiser le compte
                  </button>
                </div>
			    </form>
			    <div class="text-center">
              <p class="g-color-gray-dark-v5 mb-0">
                  <a href="/customer/login/<?= $lib->random() ?>" class="text-default g-font-weight-600">
                      Se connecter
                  </a>
              </p>
            </div>
              <!-- End Form -->
            </div>
            
          </div>

          <div class="col-md-6 order-lg-2 g-mb-80">
            <div class="mb-5">
              <h2 class="h1 g-font-weight-400 mb-3">Bienvenue sur Occaz et Neuf</h2>
              <p class="g-color-gray-dark-v4">
                OccazetNeuf est le 1er portail de vente de produits neufs et d'occasion par les professionnels de la vente.
              </p>
            </div>

            <div class="row">
              <div class="col-lg-9">
                <!-- Icon Blocks -->
                <div class="media mb-5">
                  <div class="d-flex mr-3">
                    <span class="align-self-center u-icon-v1 u-icon-size--lg g-color-primary">
                      <i class="icon-finance-168 u-line-icon-pro"></i>
                    </span>
                  </div>
                  <div class="media-body align-self-center">
                    <h3 class="h5 g-font-weight-400">Un argument ici</h3>
                    <p class="g-color-gray-dark-v5 mb-0">OccazetNeuf est le 1er portail de vente de produits neufs et d'occasion par les professionnels de la vente.</p>
                  </div>
                </div>
                <!-- End Icon Blocks -->

                <!-- Icon Blocks -->
                <div class="media mb-5">
                  <div class="d-flex mr-3">
                    <span class="align-self-center u-icon-v1 u-icon-size--lg g-color-primary">
                      <i class="icon-finance-193 u-line-icon-pro"></i>
                    </span>
                  </div>
                  <div class="media-body align-self-center">
                    <h3 class="h5 g-font-weight-400">Un autre argument ici</h3>
                    <p class="g-color-gray-dark-v5 mb-0">OccazetNeuf est le 1er portail de vente de produits neufs et d'occasion par les professionnels de la vente.</p>
                  </div>
                </div>
                <!-- End Icon Blocks -->

                <!-- Icon Blocks -->
                <div class="media">
                  <div class="d-flex mr-3">
                    <span class="align-self-center u-icon-v1 u-icon-size--lg g-color-primary">
                      <i class="icon-finance-122 u-line-icon-pro"></i>
                    </span>
                  </div>
                  <div class="media-body align-self-center">
                    <h3 class="h5 g-font-weight-400">Un dernier argument ici</h3>
                    <p class="g-color-gray-dark-v5 mb-0">OccazetNeuf est le 1er portail de vente de produits neufs et d'occasion par les professionnels de la vente.</p>
                  </div>
                </div>
                <!-- End Icon Blocks -->
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- End Reset -->

      <script charset="utf-8" type="text/javascript" src="/jsp/resetCustomer.js.php/<?php echo $currentHour?>"></script>